const state={unit:1,mode:'learn',query:'',flashIndex:0,flashOrder:[],flipped:false,known:{},done:new Set(JSON.parse(localStorage.getItem('gs7_done')||'[]'))};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const unitList=$('#unitList'),unitTitle=$('#unitTitle'),crumb=$('#crumb'),panel=$('#panel'),search=$('#search'),count=$('#count'),sourceLink=$('#sourceLink'),doneBtn=$('#doneBtn'),progressBar=$('#progressBar'),progressText=$('#progressText');
function currentUnit(){return VOCAB_DATA.find(u=>u.unit===state.unit)}
function saveDone(){localStorage.setItem('gs7_done',JSON.stringify([...state.done]));updateProgress()}
function updateProgress(){const n=state.done.size;progressBar.style.width=`${n/VOCAB_DATA.length*100}%`;progressText.textContent=`${n}/${VOCAB_DATA.length} units completed`;renderSidebar();doneBtn.textContent=state.done.has(state.unit)?'✓ Completed':'✓ Mark complete'}
function renderSidebar(){unitList.innerHTML=VOCAB_DATA.map(u=>`<button class="unit-btn ${u.unit===state.unit?'active':''} ${state.done.has(u.unit)?'done':''}" data-unit="${u.unit}"><span class="unit-num">${u.unit}</span><span class="unit-meta"><b>${u.emoji} ${u.title}</b><small>${u.words.length} native cards</small></span><span class="unit-check">✓</span></button>`).join('');$$('.unit-btn').forEach(b=>b.onclick=()=>selectUnit(+b.dataset.unit))}
function selectUnit(n){state.unit=n;state.flashIndex=0;state.flipped=false;state.query='';search.value='';const u=currentUnit();unitTitle.textContent=`${u.emoji} ${u.title}`;crumb.textContent=`UNIT ${u.unit} • GLOBAL SUCCESS 7`;sourceLink.href=u.source;doneBtn.textContent=state.done.has(n)?'✓ Completed':'✓ Mark complete';renderSidebar();resetFlash();renderMode()}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utter=new SpeechSynthesisUtterance(text);utter.lang='en-US';utter.rate=.82;const voices=window.speechSynthesis.getVoices();const us=voices.find(v=>/en-US/i.test(v.lang));if(us)utter.voice=us;window.speechSynthesis.speak(utter)}
function filteredWords(){const q=state.query.trim().toLowerCase();return currentUnit().words.filter(w=>!q||`${w.word} ${w.vi} ${w.type}`.toLowerCase().includes(q))}
function wordCard(w){return `<article class="word-card"><div class="card-top"><div class="word-icon">${w.icon||'🔤'}</div><button class="audio-btn" data-speak="${encodeURIComponent(w.word)}" title="Listen">🔊</button></div><h3>${w.word}</h3><div><span class="ipa">${w.ipa||''}</span><span class="type">${w.type||''}</span></div><div class="meaning">🇻🇳 ${w.vi}</div><p class="example">💬 ${w.example}</p></article>`}
function renderLearn(){const words=filteredWords();count.textContent=`${words.length}/${currentUnit().words.length} words`;panel.innerHTML=words.length?`<div class="vocab-grid">${words.map(wordCard).join('')}</div>`:`<div class="empty">No vocabulary found.</div>`;$$('[data-speak]').forEach(b=>b.onclick=e=>{e.stopPropagation();speak(decodeURIComponent(b.dataset.speak))})}
function resetFlash(){state.flashOrder=[...currentUnit().words.keys()];state.flashIndex=0;state.flipped=false;state.known=JSON.parse(localStorage.getItem(`gs7_known_${state.unit}`)||'{}')}
function shuffleFlash(){for(let i=state.flashOrder.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[state.flashOrder[i],state.flashOrder[j]]=[state.flashOrder[j],state.flashOrder[i]]}state.flashIndex=0;state.flipped=false;renderFlash()}
function currentFlash(){return currentUnit().words[state.flashOrder[state.flashIndex]??0]}
function markKnown(value){const w=currentFlash();state.known[w.word]=value;localStorage.setItem(`gs7_known_${state.unit}`,JSON.stringify(state.known));nextFlash()}
function nextFlash(){state.flashIndex=(state.flashIndex+1)%state.flashOrder.length;state.flipped=false;renderFlash()}
function prevFlash(){state.flashIndex=(state.flashIndex-1+state.flashOrder.length)%state.flashOrder.length;state.flipped=false;renderFlash()}
function renderFlash(){const words=currentUnit().words;if(!state.flashOrder.length)resetFlash();const w=currentFlash();const knownCount=Object.values(state.known).filter(Boolean).length;count.textContent=`${knownCount}/${words.length} remembered`;panel.innerHTML=`<div class="flash-zone"><div class="flash-meta"><span>Card ${state.flashIndex+1} / ${state.flashOrder.length}</span><span>Tap the card to flip</span></div><div class="flashcard ${state.flipped?'flipped':''}" id="flashcard"><div class="flash-inner"><div class="flash-face flash-front"><div class="flash-icon">${w.icon||'🔤'}</div><div class="flash-word">${w.word}</div><div class="flash-ipa">${w.ipa||''}</div><div class="flash-type">${w.type||''}</div><button class="audio-btn" id="flashAudio" title="Listen">🔊</button></div><div class="flash-face flash-back"><div class="flash-meaning">🇻🇳 ${w.vi}</div><div class="flash-example">${w.example}</div></div></div></div><div class="mini-progress"><span style="width:${knownCount/words.length*100}%"></span></div><div class="flash-actions"><button class="btn btn-soft" id="prevBtn">← Previous</button><button class="btn btn-red" id="againBtn">↻ Again</button><button class="btn btn-yellow" id="shuffleBtn">🔀 Shuffle</button><button class="btn btn-green" id="knowBtn">✓ I know it</button><button class="btn btn-soft" id="nextBtn">Next →</button></div></div>`;$('#flashcard').onclick=()=>{state.flipped=!state.flipped;$('#flashcard').classList.toggle('flipped',state.flipped)};$('#flashAudio').onclick=e=>{e.stopPropagation();speak(w.word)};$('#prevBtn').onclick=prevFlash;$('#nextBtn').onclick=nextFlash;$('#shuffleBtn').onclick=shuffleFlash;$('#knowBtn').onclick=()=>markKnown(true);$('#againBtn').onclick=()=>markKnown(false)}
function renderOverview(){count.textContent=`${VOCAB_DATA.reduce((s,u)=>s+u.words.length,0)} native cards`;panel.innerHTML=`<div class="overview-grid">${VOCAB_DATA.map(u=>`<button class="overview-card ${state.done.has(u.unit)?'done':''}" data-overview-unit="${u.unit}"><div class="big">${u.emoji}</div><h3>Unit ${u.unit}: ${u.title}</h3><p>${u.words.length} vocabulary cards • pronunciation • examples • flashcards</p><span class="pill">${state.done.has(u.unit)?'✓ Completed':'Start learning'}</span></button>`).join('')}</div>`;$$('[data-overview-unit]').forEach(b=>b.onclick=()=>{selectUnit(+b.dataset.overviewUnit);setMode('learn')})}
function setMode(mode){state.mode=mode;$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.mode===mode));search.style.display=mode==='learn'?'block':'none';renderMode()}
function renderMode(){if(state.mode==='learn')renderLearn();else if(state.mode==='flash')renderFlash();else renderOverview()}
search.addEventListener('input',e=>{state.query=e.target.value;renderLearn()});doneBtn.onclick=()=>{state.done.has(state.unit)?state.done.delete(state.unit):state.done.add(state.unit);saveDone()};$$('.tab').forEach(t=>t.onclick=()=>setMode(t.dataset.mode));
document.addEventListener('keydown',e=>{if(state.mode!=='flash')return;if(e.key==='ArrowRight')nextFlash();if(e.key==='ArrowLeft')prevFlash();if(e.key===' '){e.preventDefault();state.flipped=!state.flipped;renderFlash()}});
renderSidebar();selectUnit(1);updateProgress();