const SOURCE_ART={
1:{img:'https://img.loigiaihay.com/picture/2022/0313/task2-gettingstarted-u1-ta7.png',label:'Hobbies picture set'},
2:{img:'https://img.loigiaihay.com/picture/2022/0314/task2-getting-started-u2-ta7.png',label:'Healthy Living picture set'},
3:{img:'https://img.loigiaihay.com/picture/2022/0401/task3-getting-started-u3-ta7-global.png',label:'Community Service picture set'},
4:{img:'https://img.loigiaihay.com/picture/2022/0404/task4-getting-started-u4-ta7-gs.png',label:'Music and Arts picture set'},
5:{img:'https://img.loigiaihay.com/picture/2022/1123/ex1-look1-u5-ta7-global.png',label:'Food and Drink picture set'},
6:{img:'https://img.loigiaihay.com/picture/2023/0329/tieng-anh-7-unit-6-getting-started-1680056892.jpg',label:'School places picture set'},
7:{img:'https://img.loigiaihay.com/picture/2023/0329/tieng-anh-7-unit-7-getting-started-1680056901.jpg',label:'Transport picture set'},
9:{img:'https://img.loigiaihay.com/picture/2023/0329/tieng-anh-7-unit-9-getting-started-1680057133.jpg',label:'Festival picture set'},
10:{img:'https://img.loigiaihay.com/picture/2022/1103/ex4-u10-ta7-global.png',label:'Energy Sources picture set'},
11:{img:'https://img.loigiaihay.com/picture/2024/0416/1_2.png',label:'Future transport picture set'},
12:{img:'https://img.loigiaihay.com/picture/2023/0410/ex1-acloserlook1-u12-ta7-global.png',label:'English-speaking Countries picture set'}
};
const state={unit:1,mode:'learn',query:'',flashIndex:0,flashOrder:[],flipped:false,known:{},done:new Set(JSON.parse(localStorage.getItem('gs7_done')||'[]'))};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const unitList=$('#unitList'),unitTitle=$('#unitTitle'),crumb=$('#crumb'),panel=$('#panel'),search=$('#search'),count=$('#count'),sourceLink=$('#sourceLink'),doneBtn=$('#doneBtn'),progressBar=$('#progressBar'),progressText=$('#progressText');
function currentUnit(){return VOCAB_DATA.find(u=>u.unit===state.unit)}
function saveDone(){localStorage.setItem('gs7_done',JSON.stringify([...state.done]));updateProgress()}
function updateProgress(){const n=state.done.size;progressBar.style.width=`${n/VOCAB_DATA.length*100}%`;progressText.textContent=`${n}/${VOCAB_DATA.length} islands explored`;renderSidebar();doneBtn.textContent=state.done.has(state.unit)?'✓ Explored':'✓ Mark explored'}
function renderSidebar(){unitList.innerHTML=VOCAB_DATA.map(u=>`<button class="unit-btn ${u.unit===state.unit?'active':''} ${state.done.has(u.unit)?'done':''}" data-unit="${u.unit}"><span class="unit-num">${u.unit}</span><span class="unit-meta"><b>${u.emoji} ${u.title}</b><small>${u.words.length} vocabulary pearls</small></span><span class="unit-check">✓</span></button>`).join('');$$('.unit-btn').forEach(b=>b.onclick=()=>selectUnit(+b.dataset.unit))}
function selectUnit(n){state.unit=n;state.flashIndex=0;state.flipped=false;state.query='';search.value='';const u=currentUnit();unitTitle.textContent=`${u.emoji} ${u.title}`;crumb.textContent=`UNIT ${u.unit} • SUMMER OCEAN VOYAGE`;sourceLink.href=u.source;doneBtn.textContent=state.done.has(n)?'✓ Explored':'✓ Mark explored';renderSidebar();resetFlash();renderMode()}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utter=new SpeechSynthesisUtterance(text);utter.lang='en-US';utter.rate=.82;const voices=window.speechSynthesis.getVoices();const us=voices.find(v=>/en-US/i.test(v.lang));if(us)utter.voice=us;window.speechSynthesis.speak(utter)}
function filteredWords(){const q=state.query.trim().toLowerCase();return currentUnit().words.filter(w=>!q||`${w.word} ${w.vi} ${w.type}`.toLowerCase().includes(q))}
function wordArt(w){return typeof getWordSourceImage==='function'?getWordSourceImage(state.unit,w.word):null}
function wordArtHtml(w){const art=wordArt(w);if(!art)return'';return `<a class="word-source-visual" href="${art.source}" target="_blank" rel="noopener" title="${art.label}"><img src="${art.img}" alt="${art.label}: ${w.word}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" onerror="this.closest('.word-source-visual').style.display='none'"><span>🖼️ Original picture set ↗</span></a>`}
function wordCard(w){return `<article class="word-card"><div class="card-top"><div class="word-icon">${w.icon||'🐚'}</div><button class="audio-btn" data-speak="${encodeURIComponent(w.word)}" title="Listen">🔊</button></div>${wordArtHtml(w)}<h3>${w.word}</h3><div><span class="ipa">${w.ipa||''}</span><span class="type">${w.type||''}</span></div><div class="meaning">🇻🇳 ${w.vi}</div><p class="example">💬 ${w.example}</p></article>`}
function sourceArtHtml(u){const art=SOURCE_ART[u.unit];if(!art)return `<div class="source-art"><div class="source-art-copy"><span class="source-art-kicker">🌊 Original-source mode</span><h3>Unit ${u.unit} source page</h3><p>This unit does not use an AI replacement image. Open the original vocabulary page to view the source visuals exactly as published.</p><a href="${u.source}" target="_blank" rel="noopener">Open original Loigiaihay source ↗</a></div></div>`;return `<div class="source-art"><div class="source-art-media"><img src="${art.img}" alt="${art.label} from Loigiaihay" loading="lazy" referrerpolicy="no-referrer-when-downgrade" onerror="this.closest('.source-art-media').style.display='none'"></div><div class="source-art-copy"><span class="source-art-kicker">🏖️ Original illustration</span><h3>${art.label}</h3><p>This illustration is loaded directly from the original <b>img.loigiaihay.com</b> asset. It is not regenerated, redrawn or re-hosted in this repository.</p><a href="${u.source}" target="_blank" rel="noopener">View full source vocabulary page ↗</a></div></div>`}
function renderLearn(){const u=currentUnit(),words=filteredWords();count.textContent=`${words.length}/${u.words.length} words`;panel.innerHTML=sourceArtHtml(u)+(words.length?`<div class="vocab-grid">${words.map(wordCard).join('')}</div>`:`<div class="empty">No vocabulary found.</div>`);$$('[data-speak]').forEach(b=>b.onclick=e=>{e.stopPropagation();speak(decodeURIComponent(b.dataset.speak))})}
function resetFlash(){state.flashOrder=[...currentUnit().words.keys()];state.flashIndex=0;state.flipped=false;state.known=JSON.parse(localStorage.getItem(`gs7_known_${state.unit}`)||'{}')}
function shuffleFlash(){for(let i=state.flashOrder.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[state.flashOrder[i],state.flashOrder[j]]=[state.flashOrder[j],state.flashOrder[i]]}state.flashIndex=0;state.flipped=false;renderFlash()}
function currentFlash(){return currentUnit().words[state.flashOrder[state.flashIndex]??0]}
function markKnown(value){const w=currentFlash();state.known[w.word]=value;localStorage.setItem(`gs7_known_${state.unit}`,JSON.stringify(state.known));nextFlash()}
function nextFlash(){state.flashIndex=(state.flashIndex+1)%state.flashOrder.length;state.flipped=false;renderFlash()}
function prevFlash(){state.flashIndex=(state.flashIndex-1+state.flashOrder.length)%state.flashOrder.length;state.flipped=false;renderFlash()}
function renderFlash(){const words=currentUnit().words;if(!state.flashOrder.length)resetFlash();const w=currentFlash();const art=wordArt(w);const knownCount=Object.values(state.known).filter(Boolean).length;const visual=art?`<a class="flash-source-visual" href="${art.source}" target="_blank" rel="noopener" onclick="event.stopPropagation()" title="${art.label}"><img src="${art.img}" alt="${art.label}: ${w.word}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" onerror="this.closest('.flash-source-visual').style.display='none'"><small>🖼️ Original picture set ↗</small></a>`:`<div class="flash-icon">${w.icon||'🐚'}</div>`;count.textContent=`${knownCount}/${words.length} remembered`;panel.innerHTML=`<div class="flash-zone"><div class="flash-meta"><span>🐠 Card ${state.flashIndex+1} / ${state.flashOrder.length}</span><span>Tap the card to flip • collect every vocabulary pearl 🐚</span></div><div class="flashcard ${state.flipped?'flipped':''}" id="flashcard"><div class="flash-inner"><div class="flash-face flash-front">${visual}<div class="flash-word">${w.word}</div><div class="flash-ipa">${w.ipa||''}</div><div class="flash-type">${w.type||''}</div><button class="audio-btn" id="flashAudio" title="Listen">🔊</button></div><div class="flash-face flash-back"><div class="flash-meaning">🇻🇳 ${w.vi}</div><div class="flash-example">${w.example}</div>${art?`<a class="flash-source-link" href="${art.source}" target="_blank" rel="noopener" onclick="event.stopPropagation()">View original Loigiaihay picture exercise ↗</a>`:''}</div></div></div><div class="mini-progress"><span style="width:${knownCount/words.length*100}%"></span></div><div class="flash-actions"><button class="btn btn-soft" id="prevBtn">← Previous</button><button class="btn btn-red" id="againBtn">↻ Again</button><button class="btn btn-yellow" id="shuffleBtn">🔀 Shuffle</button><button class="btn btn-green" id="knowBtn">✓ I know it</button><button class="btn btn-soft" id="nextBtn">Next →</button></div></div>`;$('#flashcard').onclick=()=>{state.flipped=!state.flipped;$('#flashcard').classList.toggle('flipped',state.flipped)};$('#flashAudio').onclick=e=>{e.stopPropagation();speak(w.word)};$('#prevBtn').onclick=prevFlash;$('#nextBtn').onclick=nextFlash;$('#shuffleBtn').onclick=shuffleFlash;$('#knowBtn').onclick=()=>markKnown(true);$('#againBtn').onclick=()=>markKnown(false)}
function renderOverview(){count.textContent=`${VOCAB_DATA.reduce((s,u)=>s+u.words.length,0)} vocabulary pearls`;panel.innerHTML=`<div class="overview-grid">${VOCAB_DATA.map(u=>{const art=SOURCE_ART[u.unit];return `<button class="overview-card ${state.done.has(u.unit)?'done':''}" data-overview-unit="${u.unit}">${art?`<div class="overview-art"><img src="${art.img}" alt="${art.label}" loading="lazy" onerror="this.parentElement.style.display='none'"></div>`:`<div class="big">${u.emoji}🌊</div>`}<h3>Unit ${u.unit}: ${u.title}</h3><p>${u.words.length} vocabulary cards • pronunciation • flashcards • summer ocean mode</p><span class="pill">${state.done.has(u.unit)?'✓ Island explored':'Sail to this unit'}</span></button>`}).join('')}</div>`;$$('[data-overview-unit]').forEach(b=>b.onclick=()=>{selectUnit(+b.dataset.overviewUnit);setMode('learn')})}
function setMode(mode){state.mode=mode;$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.mode===mode));search.style.display=mode==='learn'?'block':'none';renderMode()}
function renderMode(){if(state.mode==='learn')renderLearn();else if(state.mode==='flash')renderFlash();else renderOverview()}
search.addEventListener('input',e=>{state.query=e.target.value;renderLearn()});doneBtn.onclick=()=>{state.done.has(state.unit)?state.done.delete(state.unit):state.done.add(state.unit);saveDone()};$$('.tab').forEach(t=>t.onclick=()=>setMode(t.dataset.mode));
document.addEventListener('keydown',e=>{if(state.mode!=='flash')return;if(e.key==='ArrowRight')nextFlash();if(e.key==='ArrowLeft')prevFlash();if(e.key===' '){e.preventDefault();state.flipped=!state.flipped;renderFlash()}});
renderSidebar();selectUnit(1);updateProgress();