// Phase 2 vocabulary expansion for Global Success 7.
// Terms/meanings are cross-checked against the supplied unit vocabulary pages and standard Global Success 7 lists.
// Practice examples below are newly written for this learning site. Pronunciation is handled by browser TTS in app.js.

const VOCAB_EXTRA = {
  1: [
    {word:'amazing',ipa:'/əˈmeɪzɪŋ/',type:'adj',vi:'tuyệt vời, đáng kinh ngạc',example:'Her handmade model looks amazing.',icon:'🤩'},
    {word:'arrange',ipa:'/əˈreɪndʒ/',type:'v',vi:'sắp xếp',example:'We arrange the stamps by country.',icon:'🗂️'},
    {word:'benefit',ipa:'/ˈbenɪfɪt/',type:'n',vi:'lợi ích',example:'Reading has many benefits for students.',icon:'🌟'},
    {word:'bird-watching',ipa:'/ˈbɜːd ˌwɒtʃɪŋ/',type:'n',vi:'hoạt động ngắm chim',example:'Bird-watching is relaxing in the countryside.',icon:'🐦'},
    {word:'board game',ipa:'/ˈbɔːd ɡeɪm/',type:'n',vi:'trò chơi bàn cờ',example:'We play a board game after dinner.',icon:'🎲'},
    {word:'bored with',ipa:'/bɔːd wɪð/',type:'adj phr',vi:'chán với',example:'He is bored with playing the same game.',icon:'🥱'},
    {word:'bug',ipa:'/bʌɡ/',type:'n',vi:'con bọ',example:'She found a tiny bug on a leaf.',icon:'🐞'},
    {word:'carve',ipa:'/kɑːv/',type:'v',vi:'chạm, khắc',example:'He carves small animals from wood.',icon:'🪵'},
    {word:'cardboard',ipa:'/ˈkɑːdbɔːd/',type:'n',vi:'bìa cứng',example:'Use cardboard to make the model house.',icon:'📦'},
    {word:'cheap',ipa:'/tʃiːp/',type:'adj',vi:'rẻ',example:'This hobby is cheap and easy to start.',icon:'🏷️'},
    {word:'creativity',ipa:'/ˌkriːeɪˈtɪvəti/',type:'n',vi:'sự sáng tạo',example:'Drawing can develop your creativity.',icon:'💡'},
    {word:'common',ipa:'/ˈkɒmən/',type:'adj',vi:'phổ biến, thông thường',example:'Listening to music is a common hobby.',icon:'👥'},
    {word:'competition',ipa:'/ˌkɒmpəˈtɪʃn/',type:'n',vi:'cuộc thi',example:'Our school has a model-making competition.',icon:'🏆'},
    {word:'collage',ipa:'/ˈkɒlɑːʒ/',type:'n',vi:'tranh ghép',example:'Mai makes a collage from old magazines.',icon:'🖼️'},
    {word:'insect',ipa:'/ˈɪnsekt/',type:'n',vi:'côn trùng',example:'He takes photos of insects in the garden.',icon:'🦋'},
    {word:'maturity',ipa:'/məˈtjʊərəti/',type:'n',vi:'sự trưởng thành',example:'Caring for a pet can build maturity.',icon:'🌱'},
    {word:'stress',ipa:'/stres/',type:'n',vi:'sự căng thẳng',example:'Painting helps me reduce stress.',icon:'😌'},
    {word:'yoga',ipa:'/ˈjəʊɡə/',type:'n',vi:'yoga',example:'My mother practises yoga every morning.',icon:'🧘'},
    {word:'photography',ipa:'/fəˈtɒɡrəfi/',type:'n',vi:'nhiếp ảnh',example:'Photography is his favourite weekend hobby.',icon:'📸'},
    {word:'cooking',ipa:'/ˈkʊkɪŋ/',type:'n',vi:'việc nấu ăn',example:'Cooking is useful as well as enjoyable.',icon:'👩‍🍳'},
    {word:'cycling',ipa:'/ˈsaɪklɪŋ/',type:'n',vi:'đạp xe',example:'We go cycling around the lake.',icon:'🚲'},
    {word:'flower arrangement',ipa:'/ˈflaʊə əˌreɪndʒmənt/',type:'n',vi:'nghệ thuật cắm hoa',example:'Her flower arrangement is colourful and neat.',icon:'💐'},
    {word:'collecting coins',ipa:'/kəˈlektɪŋ kɔɪnz/',type:'phrase',vi:'sưu tầm tiền xu',example:'Collecting coins teaches him about history.',icon:'🪙'},
    {word:'collecting teddy bears',ipa:'/kəˈlektɪŋ ˈtedi beəz/',type:'phrase',vi:'sưu tầm gấu bông',example:'My cousin enjoys collecting teddy bears.',icon:'🧸'},
    {word:'do yoga',ipa:'/duː ˈjəʊɡə/',type:'phrase',vi:'tập yoga',example:'I do yoga to relax after school.',icon:'🧘‍♀️'},
    {word:'play the guitar',ipa:'/pleɪ ðə ɡɪˈtɑː/',type:'phrase',vi:'chơi đàn ghi-ta',example:'Nam can play the guitar very well.',icon:'🎸'},
    {word:'develop creativity',ipa:'/dɪˈveləp ˌkriːeɪˈtɪvəti/',type:'phrase',vi:'phát triển sự sáng tạo',example:'Craft activities develop creativity.',icon:'🧠'},
    {word:'reduce stress',ipa:'/rɪˈdjuːs stres/',type:'phrase',vi:'giảm căng thẳng',example:'A relaxing hobby can reduce stress.',icon:'🌿'},
    {word:'take on responsibility',ipa:'/teɪk ɒn rɪˌspɒnsəˈbɪləti/',type:'phrase',vi:'nhận trách nhiệm',example:'Looking after fish helps children take on responsibility.',icon:'✅'},
    {word:'keep fit',ipa:'/kiːp fɪt/',type:'phrase',vi:'giữ cơ thể khỏe mạnh',example:'Jogging helps my father keep fit.',icon:'💪'},
    {word:'indoor activity',ipa:'/ˈɪndɔː ækˈtɪvəti/',type:'n',vi:'hoạt động trong nhà',example:'Making models is a good indoor activity.',icon:'🏠'},
    {word:'outdoor activity',ipa:'/ˈaʊtdɔː ækˈtɪvəti/',type:'n',vi:'hoạt động ngoài trời',example:'Cycling is my favourite outdoor activity.',icon:'🌳'},
    {word:'interested in',ipa:'/ˈɪntrəstɪd ɪn/',type:'adj phr',vi:'hứng thú với',example:'She is interested in collecting postcards.',icon:'😍'},
    {word:'read books',ipa:'/riːd bʊks/',type:'phrase',vi:'đọc sách',example:'I read books before going to bed.',icon:'📚'},
    {word:'listen to music',ipa:'/ˈlɪsn tə ˈmjuːzɪk/',type:'phrase',vi:'nghe nhạc',example:'They listen to music in their free time.',icon:'🎧'},
    {word:'a piece of cake',ipa:'/ə piːs əv keɪk/',type:'idiom',vi:'việc rất dễ',example:'Making this paper flower is a piece of cake.',icon:'🍰'},
    {word:'valuable',ipa:'/ˈvæljuəbl/',type:'adj',vi:'có giá trị, quý giá',example:'Some old stamps are very valuable.',icon:'💎'},
    {word:'popular',ipa:'/ˈpɒpjələ(r)/',type:'adj',vi:'phổ biến',example:'Football is popular with many teenagers.',icon:'🔥'},
    {word:'set',ipa:'/set/',type:'v',vi:'lặn (mặt trời)',example:'We stop cycling before the sun sets.',icon:'🌇'},
    {word:'play the violin',ipa:'/pleɪ ðə ˌvaɪəˈlɪn/',type:'phrase',vi:'chơi đàn vi-ô-lông',example:'Linh learns to play the violin on Saturdays.',icon:'🎻'},
    {word:'drawing',ipa:'/ˈdrɔːɪŋ/',type:'n',vi:'việc vẽ tranh',example:'Drawing is a hobby I can do anywhere.',icon:'✏️'}
  ],
  2: [
    {word:'boat',ipa:'/bəʊt/',type:'n',vi:'thuyền',example:'We crossed the lake in a small boat.',icon:'🚤'},
    {word:'boating',ipa:'/ˈbəʊtɪŋ/',type:'n',vi:'đi thuyền',example:'Boating is fun when the weather is calm.',icon:'🛶'},
    {word:'popular',ipa:'/ˈpɒpjələ(r)/',type:'adj',vi:'phổ biến',example:'Cycling is popular with young people.',icon:'⭐'},
    {word:'outdoor activity',ipa:'/ˈaʊtdɔː ækˈtɪvəti/',type:'n',vi:'hoạt động ngoài trời',example:'Walking is a simple outdoor activity.',icon:'🌳'},
    {word:'go cycling',ipa:'/ɡəʊ ˈsaɪklɪŋ/',type:'phrase',vi:'đi đạp xe',example:'We go cycling after school twice a week.',icon:'🚲'},
    {word:'quiet',ipa:'/ˈkwaɪət/',type:'adj',vi:'yên tĩnh',example:'Choose a quiet place to rest.',icon:'🤫'},
    {word:'interesting',ipa:'/ˈɪntrəstɪŋ/',type:'adj',vi:'thú vị',example:'This health project is very interesting.',icon:'💡'},
    {word:'lunchbox',ipa:'/ˈlʌntʃbɒks/',type:'n',vi:'hộp đựng bữa trưa',example:'Put some fruit in your lunchbox.',icon:'🍱'},
    {word:'suncream',ipa:'/ˈsʌn kriːm/',type:'n',vi:'kem chống nắng',example:'Use suncream before going outdoors.',icon:'🧴'},
    {word:'cycling',ipa:'/ˈsaɪklɪŋ/',type:'n',vi:'việc đạp xe',example:'Cycling strengthens your legs.',icon:'🚴'},
    {word:'keep fit',ipa:'/kiːp fɪt/',type:'phrase',vi:'giữ cơ thể khỏe mạnh',example:'Regular exercise helps us keep fit.',icon:'💪'},
    {word:'active',ipa:'/ˈæktɪv/',type:'adj',vi:'năng động, hoạt động nhiều',example:'Try to stay active every day.',icon:'🏃‍♀️'},
    {word:'activity',ipa:'/ækˈtɪvəti/',type:'n',vi:'hoạt động',example:'Swimming is a healthy activity.',icon:'🏊'},
    {word:'indoor',ipa:'/ˈɪndɔː(r)/',type:'adj',vi:'trong nhà',example:'Choose an indoor exercise when it rains.',icon:'🏠'},
    {word:'dim',ipa:'/dɪm/',type:'adj',vi:'mờ, thiếu sáng',example:'Do not read in a dim room.',icon:'🌘'},
    {word:'dim light',ipa:'/dɪm laɪt/',type:'n',vi:'ánh sáng mờ',example:'Dim light can make your eyes tired.',icon:'💡'},
    {word:'lip balm',ipa:'/ˈlɪp bɑːm/',type:'n',vi:'son dưỡng môi',example:'Use lip balm when your lips are dry.',icon:'💄'},
    {word:'chapped',ipa:'/tʃæpt/',type:'adj',vi:'bị nứt nẻ',example:'Cold wind can make your hands chapped.',icon:'🧤'},
    {word:'chapped lips',ipa:'/tʃæpt lɪps/',type:'n',vi:'môi nứt nẻ',example:'Drink enough water to prevent chapped lips.',icon:'👄'},
    {word:'skin',ipa:'/skɪn/',type:'n',vi:'da',example:'Clean water is good for your skin.',icon:'🫧'},
    {word:'skin condition',ipa:'/skɪn kənˈdɪʃn/',type:'n',vi:'tình trạng da',example:'Talk to a doctor about a serious skin condition.',icon:'🩺'},
    {word:'pimple',ipa:'/ˈpɪmpl/',type:'n',vi:'mụn',example:'Do not squeeze a pimple with dirty hands.',icon:'🔴'},
    {word:'pop',ipa:'/pɒp/',type:'v',vi:'nặn, làm vỡ',example:'It is better not to pop spots on your face.',icon:'⚠️'},
    {word:'protein',ipa:'/ˈprəʊtiːn/',type:'n',vi:'chất đạm',example:'Eggs are a good source of protein.',icon:'🥚'},
    {word:'soybean',ipa:'/ˈsɔɪbiːn/',type:'n',vi:'đậu nành',example:'Soybeans contain useful nutrients.',icon:'🫘'},
    {word:'tofu',ipa:'/ˈtəʊfuː/',type:'n',vi:'đậu phụ',example:'My family often adds tofu to soup.',icon:'⬜'},
    {word:'vitamin',ipa:'/ˈvɪtəmɪn/',type:'n',vi:'vitamin',example:'Fruit provides many important vitamins.',icon:'🍊'},
    {word:'soft drink',ipa:'/ˌsɒft ˈdrɪŋk/',type:'n',vi:'nước ngọt',example:'Try to drink water instead of soft drinks.',icon:'🥤'},
    {word:'affect',ipa:'/əˈfekt/',type:'v',vi:'ảnh hưởng',example:'Too little sleep can affect your health.',icon:'🔄'},
    {word:'diet',ipa:'/ˈdaɪət/',type:'n',vi:'chế độ ăn uống',example:'A balanced diet includes vegetables and protein.',icon:'🥗'},
    {word:'vegetarian',ipa:'/ˌvedʒəˈteəriən/',type:'n/adj',vi:'người ăn chay; thuộc chế độ ăn chay',example:'This restaurant has several vegetarian dishes.',icon:'🥦'},
    {word:'fat',ipa:'/fæt/',type:'n',vi:'chất béo',example:'The body needs some healthy fat.',icon:'🥑'},
    {word:'eye drops',ipa:'/ˈaɪ drɒps/',type:'n',vi:'thuốc nhỏ mắt',example:'Use eye drops only as directed.',icon:'👁️'},
    {word:'red spot',ipa:'/red spɒt/',type:'n',vi:'đốm đỏ',example:'He noticed a red spot on his arm.',icon:'🔴'},
    {word:'virus',ipa:'/ˈvaɪrəs/',type:'n',vi:'vi-rút',example:'A virus can spread from person to person.',icon:'🦠'},
    {word:'health',ipa:'/helθ/',type:'n',vi:'sức khỏe',example:'Sleep is important for good health.',icon:'❤️'},
    {word:'physical activity',ipa:'/ˈfɪzɪkl ækˈtɪvəti/',type:'n',vi:'hoạt động thể chất',example:'Children need physical activity every day.',icon:'🤸'},
    {word:'sweetened food',ipa:'/ˈswiːtnd fuːd/',type:'n',vi:'thực phẩm có thêm đường',example:'Eat less sweetened food to protect your teeth.',icon:'🍬'},
    {word:'fast food',ipa:'/ˌfɑːst ˈfuːd/',type:'n',vi:'đồ ăn nhanh',example:'We should not eat fast food too often.',icon:'🍔'},
    {word:'coloured vegetables',ipa:'/ˈkʌləd ˈvedʒtəblz/',type:'n',vi:'các loại rau củ nhiều màu sắc',example:'Add coloured vegetables to your meals.',icon:'🥕'},
    {word:'wash your hands',ipa:'/wɒʃ jɔː hændz/',type:'phrase',vi:'rửa tay',example:'Wash your hands before eating.',icon:'🧼'},
    {word:'brush your teeth',ipa:'/brʌʃ jɔː tiːθ/',type:'phrase',vi:'đánh răng',example:'Brush your teeth twice a day.',icon:'🪥'},
    {word:'touch your face',ipa:'/tʌtʃ jɔː feɪs/',type:'phrase',vi:'chạm tay lên mặt',example:'Avoid touching your face with dirty hands.',icon:'🙅'},
    {word:'wear a mask',ipa:'/weə ə mɑːsk/',type:'phrase',vi:'đeo khẩu trang',example:'Wear a mask when you have the flu.',icon:'😷'},
    {word:'keep your surroundings clean',ipa:'/kiːp jɔː səˈraʊndɪŋz kliːn/',type:'phrase',vi:'giữ môi trường xung quanh sạch sẽ',example:'Keep your surroundings clean to reduce germs.',icon:'🧹'},
    {word:'take care of',ipa:'/teɪk keər əv/',type:'phr v',vi:'chăm sóc',example:'Take care of your eyes when using screens.',icon:'🤲'},
    {word:'put on weight',ipa:'/pʊt ɒn weɪt/',type:'phrase',vi:'tăng cân',example:'Eating too much can make you put on weight.',icon:'⚖️'}
  ],
  3: [
    {word:'community',ipa:'/kəˈmjuːnəti/',type:'n',vi:'cộng đồng',example:'Our community works together to keep the park clean.',icon:'🏘️'},
    {word:'community activity',ipa:'/kəˈmjuːnəti ækˈtɪvəti/',type:'n',vi:'hoạt động cộng đồng',example:'Tree planting is a useful community activity.',icon:'🤝'},
    {word:'board game',ipa:'/ˈbɔːd ɡeɪm/',type:'n',vi:'trò chơi bàn cờ',example:'Volunteers play board games with elderly people.',icon:'🎲'},
    {word:'clean-up activity',ipa:'/ˈkliːn ʌp ækˈtɪvəti/',type:'n',vi:'hoạt động dọn vệ sinh',example:'Our class joined a clean-up activity near the canal.',icon:'🧹'},
    {word:'collect',ipa:'/kəˈlekt/',type:'v',vi:'thu gom, sưu tầm',example:'We collect used paper for recycling.',icon:'📦'},
    {word:'develop',ipa:'/dɪˈveləp/',type:'v',vi:'phát triển',example:'Volunteering helps students develop useful skills.',icon:'📈'},
    {word:'exchange',ipa:'/ɪksˈtʃeɪndʒ/',type:'v',vi:'trao đổi',example:'Students exchange used paper for notebooks.',icon:'🔁'},
    {word:'flooded',ipa:'/ˈflʌdɪd/',type:'adj',vi:'bị ngập lụt',example:'The group sent food to flooded villages.',icon:'🌊'},
    {word:'mountainous',ipa:'/ˈmaʊntənəs/',type:'adj',vi:'thuộc vùng núi',example:'They donated books to a mountainous school.',icon:'⛰️'},
    {word:'orphanage',ipa:'/ˈɔːfənɪdʒ/',type:'n',vi:'trại trẻ mồ côi',example:'Our club visited a local orphanage.',icon:'🏡'},
    {word:'plant',ipa:'/plɑːnt/',type:'v',vi:'trồng',example:'We plant flowers beside the school gate.',icon:'🌱'},
    {word:'protect',ipa:'/prəˈtekt/',type:'v',vi:'bảo vệ',example:'These projects help protect the environment.',icon:'🛡️'},
    {word:'pick up',ipa:'/pɪk ʌp/',type:'phr v',vi:'nhặt lên, thu gom',example:'Please pick up the bottles on the ground.',icon:'🗑️'},
    {word:'proud',ipa:'/praʊd/',type:'adj',vi:'tự hào',example:'We are proud of our volunteer team.',icon:'😊'},
    {word:'recycle',ipa:'/ˌriːˈsaɪkl/',type:'v',vi:'tái chế',example:'Our school recycles paper and plastic.',icon:'♻️'},
    {word:'rural area',ipa:'/ˈrʊərəl ˈeəriə/',type:'n',vi:'khu vực nông thôn',example:'The charity supports children in rural areas.',icon:'🌾'},
    {word:'skill',ipa:'/skɪl/',type:'n',vi:'kỹ năng',example:'Teamwork is an important life skill.',icon:'🧠'},
    {word:'teenager',ipa:'/ˈtiːneɪdʒə(r)/',type:'n',vi:'thiếu niên',example:'Many teenagers join volunteer clubs.',icon:'🧑'},
    {word:'water',ipa:'/ˈwɔːtə(r)/',type:'v',vi:'tưới nước',example:'We water the young trees every afternoon.',icon:'💧'},
    {word:'decorate',ipa:'/ˈdekəreɪt/',type:'v',vi:'trang trí',example:'Students decorate the community room with drawings.',icon:'🎨'},
    {word:'street children',ipa:'/striːt ˈtʃɪldrən/',type:'n',vi:'trẻ em đường phố',example:'The programme provides meals for street children.',icon:'🧒'},
    {word:'sell',ipa:'/sel/',type:'v',vi:'bán',example:'We sell handmade cards to raise funds.',icon:'🛍️'},
    {word:'famous',ipa:'/ˈfeɪməs/',type:'adj',vi:'nổi tiếng',example:'A famous singer supported the charity event.',icon:'🌟'},
    {word:'bamboo',ipa:'/ˌbæmˈbuː/',type:'n',vi:'tre, trúc',example:'They made simple gifts from bamboo.',icon:'🎋'},
    {word:'bring',ipa:'/brɪŋ/',type:'v',vi:'mang, đem',example:'Please bring old books for the donation box.',icon:'📚'},
    {word:'set up',ipa:'/set ʌp/',type:'phr v',vi:'thành lập, thiết lập',example:'Students set up a small recycling club.',icon:'🛠️'},
    {word:'solution',ipa:'/səˈluːʃn/',type:'n',vi:'giải pháp',example:'Recycling is one solution to plastic waste.',icon:'💡'},
    {word:'environmental problems',ipa:'/ɪnˌvaɪrənˈmentl ˈprɒbləmz/',type:'n',vi:'các vấn đề môi trường',example:'The class discusses local environmental problems.',icon:'🌍'},
    {word:'solve',ipa:'/sɒlv/',type:'v',vi:'giải quyết',example:'Young volunteers can help solve community problems.',icon:'🧩'},
    {word:'meet up',ipa:'/miːt ʌp/',type:'phr v',vi:'gặp nhau',example:'The volunteers meet up at school on Saturday.',icon:'👋'},
    {word:'plant vegetables',ipa:'/plɑːnt ˈvedʒtəblz/',type:'phrase',vi:'trồng rau',example:'We plant vegetables in the community garden.',icon:'🥬'},
    {word:'make a difference',ipa:'/meɪk ə ˈdɪfrəns/',type:'phrase',vi:'tạo ra sự thay đổi tích cực',example:'Even a small action can make a difference.',icon:'✨'},
    {word:'disabled people',ipa:'/dɪsˈeɪbld ˈpiːpl/',type:'n',vi:'người khuyết tật',example:'The centre offers activities for disabled people.',icon:'♿'}
  ]
};

Object.entries(VOCAB_EXTRA).forEach(([unitNo, extraWords]) => {
  const unit = VOCAB_DATA.find(item => item.unit === Number(unitNo));
  if (!unit) return;
  const seen = new Set(unit.words.map(item => item.word.trim().toLowerCase()));
  extraWords.forEach(item => {
    const key = item.word.trim().toLowerCase();
    if (!seen.has(key)) {
      unit.words.push(item);
      seen.add(key);
    }
  });
});
