// Phase 3 vocabulary expansion: Units 4–6.
// Vocabulary is cross-checked against the supplied Global Success 7 unit pages and supporting lesson resources.
// Practice examples are newly written; pronunciation continues to use browser TTS.

const VOCAB_EXTRA_2 = {
  4: [
    {word:'listening to music',ipa:'/ˈlɪsnɪŋ tə ˈmjuːzɪk/',type:'phrase',vi:'nghe nhạc',example:'Listening to music helps me relax.',icon:'🎧'},
    {word:'play the piano',ipa:'/pleɪ ðə piˈænəʊ/',type:'phrase',vi:'chơi đàn piano',example:'My sister can play the piano.',icon:'🎹'},
    {word:'play musical instruments',ipa:'/pleɪ ˈmjuːzɪkl ˈɪnstrəmənts/',type:'phrase',vi:'chơi nhạc cụ',example:'Students learn to play musical instruments at school.',icon:'🎶'},
    {word:'painting',ipa:'/ˈpeɪntɪŋ/',type:'n',vi:'hội họa; bức tranh',example:'This painting shows a peaceful village.',icon:'🖌️'},
    {word:'drawing',ipa:'/ˈdrɔːɪŋ/',type:'n',vi:'việc vẽ; bức vẽ',example:'Her drawing won first prize.',icon:'✏️'},
    {word:'photography',ipa:'/fəˈtɒɡrəfi/',type:'n',vi:'nhiếp ảnh',example:'Photography can turn daily moments into art.',icon:'📷'},
    {word:'camera',ipa:'/ˈkæmərə/',type:'n',vi:'máy ảnh',example:'He uses a camera to take street photos.',icon:'📸'},
    {word:'drum',ipa:'/drʌm/',type:'n',vi:'trống',example:'The drummer plays the drum loudly.',icon:'🥁'},
    {word:'guitar',ipa:'/ɡɪˈtɑː(r)/',type:'n',vi:'đàn ghi-ta',example:'The guitar sounds warm and clear.',icon:'🎸'},
    {word:'piano',ipa:'/piˈænəʊ/',type:'n',vi:'đàn piano',example:'There is a piano in the music room.',icon:'🎹'},
    {word:'violin',ipa:'/ˌvaɪəˈlɪn/',type:'n',vi:'đàn vi-ô-lông',example:'She practises the violin every evening.',icon:'🎻'},
    {word:'saxophone',ipa:'/ˈsæksəfəʊn/',type:'n',vi:'kèn saxophone',example:'The saxophone is common in jazz music.',icon:'🎷'},
    {word:'flute',ipa:'/fluːt/',type:'n',vi:'sáo',example:'He plays a soft tune on the flute.',icon:'🪈'},
    {word:'cello',ipa:'/ˈtʃeləʊ/',type:'n',vi:'đàn cello',example:'The cello has a deep sound.',icon:'🎻'},
    {word:'actor',ipa:'/ˈæktə(r)/',type:'n',vi:'nam diễn viên',example:'The actor performs in a school play.',icon:'🎭'},
    {word:'actress',ipa:'/ˈæktrəs/',type:'n',vi:'nữ diễn viên',example:'The actress greeted the audience after the show.',icon:'🎬'},
    {word:'dancer',ipa:'/ˈdɑːnsə(r)/',type:'n',vi:'vũ công',example:'The dancer moves beautifully with the music.',icon:'💃'},
    {word:'art form',ipa:'/ɑːt fɔːm/',type:'n',vi:'loại hình nghệ thuật',example:'Water puppetry is a traditional art form.',icon:'🎨'},
    {word:'rice farming',ipa:'/raɪs ˈfɑːmɪŋ/',type:'n',vi:'việc trồng lúa',example:'The puppet show tells a story about rice farming.',icon:'🌾'},
    {word:'exciting',ipa:'/ɪkˈsaɪtɪŋ/',type:'adj',vi:'sôi nổi, thú vị',example:'The live concert was exciting.',icon:'🤩'},
    {word:'pop music',ipa:'/pɒp ˈmjuːzɪk/',type:'n',vi:'nhạc pop',example:'Many teenagers enjoy pop music.',icon:'🎤'},
    {word:'country music',ipa:'/ˈkʌntri ˈmjuːzɪk/',type:'n',vi:'nhạc đồng quê',example:'My uncle listens to country music while driving.',icon:'🤠'},
    {word:'works of art',ipa:'/wɜːks əv ɑːt/',type:'n',vi:'các tác phẩm nghệ thuật',example:'The museum displays many works of art.',icon:'🖼️'},
    {word:'opera',ipa:'/ˈɒprə/',type:'n',vi:'nhạc kịch',example:'We watched an opera at the theatre.',icon:'🎭'},
    {word:'beat',ipa:'/biːt/',type:'n',vi:'nhịp',example:'This song has a strong beat.',icon:'🥁'},
    {word:'compulsory',ipa:'/kəmˈpʌlsəri/',type:'adj',vi:'bắt buộc',example:'Music is compulsory in their school.',icon:'📌'},
    {word:'choir',ipa:'/ˈkwaɪə(r)/',type:'n',vi:'dàn hợp xướng',example:'The school choir sings every month.',icon:'🎶'},
    {word:'optional',ipa:'/ˈɒpʃənl/',type:'adj',vi:'tự chọn, không bắt buộc',example:'Drama is an optional subject here.',icon:'☑️'},
    {word:'drama',ipa:'/ˈdrɑːmə/',type:'n',vi:'kịch; môn kịch',example:'Our drama club is preparing a new play.',icon:'🎭'},
    {word:'dancing',ipa:'/ˈdɑːnsɪŋ/',type:'n',vi:'khiêu vũ, nhảy múa',example:'Dancing is part of the school performance.',icon:'🕺'},
    {word:'art club',ipa:'/ɑːt klʌb/',type:'n',vi:'câu lạc bộ nghệ thuật',example:'I joined the art club this term.',icon:'🎨'},
    {word:'street painting',ipa:'/striːt ˈpeɪntɪŋ/',type:'n',vi:'nghệ thuật vẽ đường phố',example:'Street painting turns the pavement into a gallery.',icon:'🛣️'},
    {word:'pavement',ipa:'/ˈpeɪvmənt/',type:'n',vi:'vỉa hè, mặt đường dành cho người đi bộ',example:'Artists draw colourful pictures on the pavement.',icon:'🧱'},
    {word:'chalk',ipa:'/tʃɔːk/',type:'n',vi:'phấn',example:'The artist uses chalk to draw on the street.',icon:'🖍️'},
    {word:'festival',ipa:'/ˈfestɪvl/',type:'n',vi:'lễ hội',example:'The street art festival attracts many visitors.',icon:'🎉'},
    {word:'exhibition',ipa:'/ˌeksɪˈbɪʃn/',type:'n',vi:'triển lãm',example:'Our class organised an art exhibition.',icon:'🏛️'},
    {word:'art collection',ipa:'/ɑːt kəˈlekʃn/',type:'n',vi:'bộ sưu tập nghệ thuật',example:'The gallery has a large art collection.',icon:'🖼️'},
    {word:'visitor',ipa:'/ˈvɪzɪtə(r)/',type:'n',vi:'khách tham quan',example:'Each visitor receives a festival map.',icon:'👥'},
    {word:'invite',ipa:'/ɪnˈvaɪt/',type:'v',vi:'mời',example:'We invite our parents to the music show.',icon:'💌'},
    {word:'event',ipa:'/ɪˈvent/',type:'n',vi:'sự kiện',example:'The art event starts at seven o’clock.',icon:'📅'},
    {word:'show',ipa:'/ʃəʊ/',type:'n',vi:'buổi biểu diễn',example:'The music show lasts for an hour.',icon:'🎟️'},
    {word:'artistic',ipa:'/ɑːˈtɪstɪk/',type:'adj',vi:'có năng khiếu nghệ thuật; thuộc nghệ thuật',example:'Lan is artistic and loves drawing portraits.',icon:'✨'}
  ],
  5: [
    {word:'food',ipa:'/fuːd/',type:'n',vi:'thức ăn',example:'Fresh food is important for a healthy meal.',icon:'🍽️'},
    {word:'drink',ipa:'/drɪŋk/',type:'n',vi:'đồ uống',example:'Water is my favourite drink.',icon:'🥤'},
    {word:'rice',ipa:'/raɪs/',type:'n',vi:'cơm, gạo',example:'We usually eat rice with vegetables.',icon:'🍚'},
    {word:'pork',ipa:'/pɔːk/',type:'n',vi:'thịt heo',example:'My mother cooks pork with eggs.',icon:'🥩'},
    {word:'fish',ipa:'/fɪʃ/',type:'n',vi:'cá',example:'Grilled fish goes well with rice.',icon:'🐟'},
    {word:'fish sauce',ipa:'/fɪʃ sɔːs/',type:'n',vi:'nước mắm',example:'Add a little fish sauce to the soup.',icon:'🧂'},
    {word:'roast chicken',ipa:'/rəʊst ˈtʃɪkɪn/',type:'n',vi:'gà quay',example:'We ordered roast chicken for dinner.',icon:'🍗'},
    {word:'fried vegetables',ipa:'/fraɪd ˈvedʒtəblz/',type:'n',vi:'rau xào, rau chiên',example:'The restaurant serves fried vegetables with rice.',icon:'🥦'},
    {word:'fried tofu',ipa:'/fraɪd ˈtəʊfuː/',type:'n',vi:'đậu phụ chiên',example:'Fried tofu is crispy outside.',icon:'⬜'},
    {word:'eel',ipa:'/iːl/',type:'n',vi:'lươn',example:'Eel is used in several local dishes.',icon:'🐟'},
    {word:'eel soup',ipa:'/iːl suːp/',type:'n',vi:'súp lươn',example:'This town is famous for eel soup.',icon:'🍲'},
    {word:'toast',ipa:'/təʊst/',type:'n',vi:'bánh mì nướng',example:'I have toast and milk for breakfast.',icon:'🍞'},
    {word:'milk',ipa:'/mɪlk/',type:'n',vi:'sữa',example:'She drinks a glass of milk every morning.',icon:'🥛'},
    {word:'sugar',ipa:'/ˈʃʊɡə(r)/',type:'n',vi:'đường',example:'Do not add too much sugar.',icon:'🧂'},
    {word:'salt',ipa:'/sɔːlt/',type:'n',vi:'muối',example:'The soup needs a little salt.',icon:'🧂'},
    {word:'flour',ipa:'/ˈflaʊə(r)/',type:'n',vi:'bột mì',example:'We need flour to make the cake.',icon:'🌾'},
    {word:'onion',ipa:'/ˈʌnjən/',type:'n',vi:'hành tây',example:'Slice one onion for the soup.',icon:'🧅'},
    {word:'chili',ipa:'/ˈtʃɪli/',type:'n',vi:'ớt',example:'This chili is very spicy.',icon:'🌶️'},
    {word:'water',ipa:'/ˈwɔːtə(r)/',type:'n',vi:'nước',example:'Drink enough water every day.',icon:'💧'},
    {word:'mineral water',ipa:'/ˈmɪnərəl ˈwɔːtə(r)/',type:'n',vi:'nước khoáng',example:'He ordered a bottle of mineral water.',icon:'💦'},
    {word:'juice',ipa:'/dʒuːs/',type:'n',vi:'nước ép',example:'Would you like some orange juice?',icon:'🧃'},
    {word:'winter melon juice',ipa:'/ˈwɪntə ˈmelən dʒuːs/',type:'n',vi:'nước bí đao',example:'Winter melon juice is served cold.',icon:'🧃'},
    {word:'tea',ipa:'/tiː/',type:'n',vi:'trà',example:'My grandmother drinks tea after breakfast.',icon:'🍵'},
    {word:'green tea',ipa:'/ɡriːn tiː/',type:'n',vi:'trà xanh',example:'Green tea has a light flavour.',icon:'🍵'},
    {word:'coffee',ipa:'/ˈkɒfi/',type:'n',vi:'cà phê',example:'My father likes coffee without sugar.',icon:'☕'},
    {word:'order',ipa:'/ˈɔːdə(r)/',type:'v/n',vi:'gọi món; đơn gọi món',example:'We are ready to order our food.',icon:'📝'},
    {word:'prepare',ipa:'/prɪˈpeə(r)/',type:'v',vi:'chuẩn bị',example:'Prepare the vegetables before cooking.',icon:'🔪'},
    {word:'cook',ipa:'/kʊk/',type:'v',vi:'nấu ăn',example:'Cook the noodles for five minutes.',icon:'👩‍🍳'},
    {word:'stew',ipa:'/stjuː/',type:'v/n',vi:'hầm; món hầm',example:'We stew the meat until it is soft.',icon:'🍲'},
    {word:'broth',ipa:'/brɒθ/',type:'n',vi:'nước dùng',example:'The broth smells fragrant.',icon:'🥣'},
    {word:'fork',ipa:'/fɔːk/',type:'n',vi:'nĩa',example:'Use a fork to eat the salad.',icon:'🍴'},
    {word:'teaspoon',ipa:'/ˈtiːspuːn/',type:'n',vi:'thìa cà phê',example:'Add one teaspoon of sugar.',icon:'🥄'},
    {word:'tablespoon',ipa:'/ˈteɪblspuːn/',type:'n',vi:'thìa canh',example:'Pour two tablespoons of oil into the pan.',icon:'🥄'},
    {word:'glass',ipa:'/ɡlɑːs/',type:'n',vi:'cốc thủy tinh',example:'She drank a glass of lemonade.',icon:'🥛'},
    {word:'cup',ipa:'/kʌp/',type:'n',vi:'tách, cốc',example:'Would you like a cup of tea?',icon:'☕'},
    {word:'beat',ipa:'/biːt/',type:'v',vi:'đánh, khuấy',example:'Beat the eggs in a bowl.',icon:'🥣'},
    {word:'bitter',ipa:'/ˈbɪtə(r)/',type:'adj',vi:'đắng',example:'The coffee tastes bitter without sugar.',icon:'☕'},
    {word:'delicious',ipa:'/dɪˈlɪʃəs/',type:'adj',vi:'ngon',example:'This noodle soup is delicious.',icon:'😋'},
    {word:'fold',ipa:'/fəʊld/',type:'v',vi:'gấp',example:'Fold the pancake carefully around the filling.',icon:'🥞'},
    {word:'fragrant',ipa:'/ˈfreɪɡrənt/',type:'adj',vi:'thơm',example:'The hot soup is fragrant with herbs.',icon:'🌿'},
    {word:'noodles',ipa:'/ˈnuːdlz/',type:'n',vi:'mì, bún, phở dạng sợi',example:'Put the noodles into a large bowl.',icon:'🍜'},
    {word:'pour',ipa:'/pɔː(r)/',type:'v',vi:'rót, đổ',example:'Pour the broth over the noodles.',icon:'🫗'},
    {word:'sauce',ipa:'/sɔːs/',type:'n',vi:'nước sốt',example:'This sauce is sweet and spicy.',icon:'🥫'}
  ],
  6: [
    {word:'classmate',ipa:'/ˈklɑːsmeɪt/',type:'n',vi:'bạn cùng lớp',example:'My classmate showed me the new library.',icon:'🧑‍🤝‍🧑'},
    {word:'school library',ipa:'/skuːl ˈlaɪbrəri/',type:'n',vi:'thư viện trường',example:'We borrow books from the school library.',icon:'📚'},
    {word:'take photos',ipa:'/teɪk ˈfəʊtəʊz/',type:'phrase',vi:'chụp ảnh',example:'Visitors can take photos in the school garden.',icon:'📸'},
    {word:'remind',ipa:'/rɪˈmaɪnd/',type:'v',vi:'nhắc nhở',example:'Please remind me about the school visit.',icon:'⏰'},
    {word:'magazine',ipa:'/ˌmæɡəˈziːn/',type:'n',vi:'tạp chí',example:'The library has English magazines for students.',icon:'📰'},
    {word:'school garden',ipa:'/skuːl ˈɡɑːdn/',type:'n',vi:'vườn trường',example:'Students grow vegetables in the school garden.',icon:'🌱'},
    {word:'playground',ipa:'/ˈpleɪɡraʊnd/',type:'n',vi:'sân chơi',example:'The children play basketball in the playground.',icon:'🏀'},
    {word:'Biology',ipa:'/baɪˈɒlədʒi/',type:'n',vi:'môn Sinh học',example:'We study plants in Biology.',icon:'🧬'},
    {word:'science lab',ipa:'/ˈsaɪəns læb/',type:'n',vi:'phòng thí nghiệm khoa học',example:'The science lab has modern equipment.',icon:'🧪'},
    {word:'Information Technology',ipa:'/ˌɪnfəˈmeɪʃn tekˈnɒlədʒi/',type:'n',vi:'môn Công nghệ thông tin',example:'Information Technology is taught in the computer room.',icon:'💻'},
    {word:'Physical Education',ipa:'/ˌfɪzɪkl edʒuˈkeɪʃn/',type:'n',vi:'môn Giáo dục thể chất',example:'We have Physical Education on Friday.',icon:'🏃'},
    {word:'History',ipa:'/ˈhɪstri/',type:'n',vi:'môn Lịch sử',example:'History is my favourite school subject.',icon:'📜'},
    {word:'computer room',ipa:'/kəmˈpjuːtə ruːm/',type:'n',vi:'phòng máy tính',example:'Our computer room has thirty computers.',icon:'🖥️'},
    {word:'entrance exam',ipa:'/ˈentrəns ɪɡˌzæm/',type:'n',vi:'kỳ thi đầu vào',example:'Students take an entrance exam for the school.',icon:'📝'},
    {word:'entrance examination',ipa:'/ˈentrəns ɪɡˌzæmɪˈneɪʃn/',type:'n',vi:'kỳ thi đầu vào',example:'The entrance examination is held in June.',icon:'📄'},
    {word:'outdoor activities',ipa:'/ˈaʊtdɔːr ækˈtɪvətiz/',type:'n',vi:'các hoạt động ngoài trời',example:'The school organises outdoor activities every month.',icon:'🌳'},
    {word:'equipment',ipa:'/ɪˈkwɪpmənt/',type:'n',vi:'thiết bị, đồ dùng',example:'The gym has new sports equipment.',icon:'🧰'},
    {word:'facility',ipa:'/fəˈsɪləti/',type:'n',vi:'cơ sở vật chất, tiện nghi',example:'The library is an important school facility.',icon:'🏫'},
    {word:'extra',ipa:'/ˈekstrə/',type:'adj',vi:'thêm, bổ sung',example:'Students can choose extra subjects.',icon:'➕'},
    {word:'midterm',ipa:'/ˌmɪdˈtɜːm/',type:'adj/n',vi:'giữa học kỳ; bài thi giữa kỳ',example:'Our midterm test is next Monday.',icon:'📝'},
    {word:'projector',ipa:'/prəˈdʒektə(r)/',type:'n',vi:'máy chiếu',example:'The teacher uses a projector in class.',icon:'📽️'},
    {word:'resource',ipa:'/rɪˈsɔːs/',type:'n',vi:'tài nguyên',example:'The website is a useful learning resource.',icon:'📚'},
    {word:'royal',ipa:'/ˈrɔɪəl/',type:'adj',vi:'thuộc hoàng gia',example:'The old school once educated royal children.',icon:'👑'},
    {word:'service',ipa:'/ˈsɜːvɪs/',type:'n',vi:'dịch vụ',example:'The school offers a bus service.',icon:'🚌'},
    {word:'share',ipa:'/ʃeə(r)/',type:'v',vi:'chia sẻ',example:'Students share learning materials with classmates.',icon:'🤝'},
    {word:'talented',ipa:'/ˈtæləntɪd/',type:'adj',vi:'tài năng',example:'The school has many talented young musicians.',icon:'🌟'},
    {word:'learning resources',ipa:'/ˈlɜːnɪŋ rɪˈsɔːsɪz/',type:'n',vi:'tài liệu, nguồn học tập',example:'The library provides many learning resources.',icon:'📚'},
    {word:'sport hall',ipa:'/spɔːt hɔːl/',type:'n',vi:'nhà thi đấu thể thao',example:'Students practise volleyball in the sport hall.',icon:'🏟️'},
    {word:'get involved in',ipa:'/ɡet ɪnˈvɒlvd ɪn/',type:'phrase',vi:'tham gia vào',example:'Students get involved in many school projects.',icon:'🙋'},
    {word:'Christmas Day',ipa:'/ˈkrɪsməs deɪ/',type:'n',vi:'Ngày Giáng sinh',example:'The school is closed on Christmas Day.',icon:'🎄'},
    {word:'finish',ipa:'/ˈfɪnɪʃ/',type:'v',vi:'kết thúc',example:'The school year finishes in May.',icon:'🏁'},
    {word:'play badminton',ipa:'/pleɪ ˈbædmɪntən/',type:'phrase',vi:'chơi cầu lông',example:'We play badminton after class.',icon:'🏸'},
    {word:'break time',ipa:'/breɪk taɪm/',type:'n',vi:'giờ giải lao',example:'Students talk with friends at break time.',icon:'⏸️'},
    {word:'gym',ipa:'/dʒɪm/',type:'n',vi:'phòng tập thể dục',example:'The school gym is beside the playground.',icon:'🏋️'},
    {word:'gifted students',ipa:'/ˈɡɪftɪd ˈstjuːdnts/',type:'n',vi:'học sinh năng khiếu',example:'The programme supports gifted students.',icon:'🌟'},
    {word:'intelligent',ipa:'/ɪnˈtelɪdʒənt/',type:'adj',vi:'thông minh',example:'The students are intelligent and hardworking.',icon:'🧠'},
    {word:'staffroom',ipa:'/ˈstɑːfruːm/',type:'n',vi:'phòng giáo viên',example:'Teachers meet in the staffroom at lunchtime.',icon:'👩‍🏫'},
    {word:'school trip',ipa:'/skuːl trɪp/',type:'n',vi:'chuyến đi của trường',example:'Our school trip starts early on Saturday.',icon:'🚌'},
    {word:'activity studio',ipa:'/ækˈtɪvəti ˈstjuːdiəʊ/',type:'n',vi:'phòng hoạt động',example:'Students practise drama in the activity studio.',icon:'🎭'}
  ]
};

Object.entries(VOCAB_EXTRA_2).forEach(([unitNo, extraWords]) => {
  const unit = VOCAB_DATA.find(item => item.unit === Number(unitNo));
  if (!unit) return;
  const seen = new Set(unit.words.map(item => item.word.trim().toLowerCase()));
  extraWords.forEach(item => {
    const key = item.word.trim().toLowerCase();
    if (!seen.has(key)) {
      unit.words.push(item);
      seen.add(key);
    }
  });
});
