// Phase 5 vocabulary expansion: Units 10–12.
// Coverage targets follow the supplied Loigiaihay Global Success 7 unit pages.
// Practice examples are newly written; pronunciation continues to use browser TTS.

const rowsToWords4 = rows => rows.map(([word, ipa, type, vi, example, icon]) => ({word, ipa, type, vi, example, icon}));

const VOCAB_EXTRA_4 = {
  10: rowsToWords4([
    ['oil','/ɔɪl/','n','dầu mỏ','Oil is a non-renewable energy source.','🛢️'],
    ['hydro energy','/ˈhaɪdrəʊ ˈenədʒi/','n','năng lượng thủy điện','Hydro energy uses moving water to make electricity.','💧'],
    ['water energy','/ˈwɔːtə ˈenədʒi/','n','năng lượng nước','Water energy is renewable.','🌊'],
    ['wind turbine','/wɪnd ˈtɜːbaɪn/','n','tuabin gió','The wind turbine turns when the wind blows.','🌬️'],
    ['power station','/ˈpaʊə ˌsteɪʃn/','n','nhà máy điện','The power station supplies electricity to the town.','🏭'],
    ['generate','/ˈdʒenəreɪt/','v','tạo ra, phát điện','Solar panels generate electricity.','⚡'],
    ['consume','/kənˈsjuːm/','v','tiêu thụ','Old machines consume a lot of energy.','🔌'],
    ['consumption','/kənˈsʌmpʃn/','n','sự tiêu thụ','We should reduce electricity consumption.','📉'],
    ['resource','/rɪˈsɔːs/','n','tài nguyên','Coal is a limited natural resource.','🌍'],
    ['limited','/ˈlɪmɪtɪd/','adj','có giới hạn','Fossil fuels are limited.','⏳'],
    ['unlimited','/ʌnˈlɪmɪtɪd/','adj','không giới hạn','Sunlight is almost unlimited in some places.','♾️'],
    ['abundant','/əˈbʌndənt/','adj','dồi dào','Wind energy is abundant near the coast.','🌬️'],
    ['cheap','/tʃiːp/','adj','rẻ','This energy source is cheap to use.','💰'],
    ['expensive','/ɪkˈspensɪv/','adj','đắt','Installing new panels can be expensive.','💸'],
    ['clean energy','/kliːn ˈenədʒi/','n','năng lượng sạch','Solar power is a form of clean energy.','🌱'],
    ['polluting','/pəˈluːtɪŋ/','adj','gây ô nhiễm','Coal is a polluting fuel.','🏭'],
    ['harmful','/ˈhɑːmfl/','adj','có hại','Dirty smoke is harmful to the environment.','⚠️'],
    ['environment','/ɪnˈvaɪrənmənt/','n','môi trường','Renewable energy is better for the environment.','🌿'],
    ['pollution','/pəˈluːʃn/','n','ô nhiễm','Clean energy can reduce air pollution.','🌫️'],
    ['carbon dioxide','/ˌkɑːbən daɪˈɒksaɪd/','n','khí cacbonic','Burning coal releases carbon dioxide.','💨'],
    ['greenhouse gas','/ˈɡriːnhaʊs ɡæs/','n','khí nhà kính','Carbon dioxide is a greenhouse gas.','🌡️'],
    ['install','/ɪnˈstɔːl/','v','lắp đặt','They will install solar panels on the roof.','🔧'],
    ['turbine','/ˈtɜːbaɪn/','n','tuabin','The turbine produces electricity from wind.','🌀'],
    ['dam','/dæm/','n','đập nước','The dam stores water for the power station.','🌊'],
    ['electricity bill','/ɪˌlekˈtrɪsəti bɪl/','n','hóa đơn tiền điện','Turning off lights can lower the electricity bill.','🧾'],
    ['run out','/rʌn aʊt/','phr v','cạn kiệt','Fossil fuels may run out one day.','⌛'],
    ['alternative energy','/ɔːlˈtɜːnətɪv ˈenədʒi/','n','năng lượng thay thế','Scientists are developing alternative energy sources.','♻️'],
    ['biogas','/ˈbaɪəʊɡæs/','n','khí sinh học','Some farms produce biogas from animal waste.','🐄'],
    ['biomass','/ˈbaɪəʊmæs/','n','sinh khối','Wood and plant waste can be used as biomass.','🌾'],
    ['hydroelectric power','/ˌhaɪdrəʊɪˈlektrɪk ˈpaʊə(r)/','n','thủy điện','Hydroelectric power comes from moving water.','💦'],
    ['sunlight','/ˈsʌnlaɪt/','n','ánh nắng mặt trời','Solar panels turn sunlight into electricity.','☀️'],
    ['wind power','/wɪnd ˈpaʊə(r)/','n','điện gió','Wind power is growing quickly in coastal areas.','🌬️'],
    ['energy-efficient','/ˈenədʒi ɪˌfɪʃnt/','adj','tiết kiệm năng lượng','Energy-efficient bulbs use less electricity.','💡'],
    ['switch off','/swɪtʃ ɒf/','phr v','tắt','Switch off the fan when you leave.','🔘'],
    ['turn off','/tɜːn ɒf/','phr v','tắt','Turn off unused lights to save energy.','💡'],
    ['energy-saving','/ˈenədʒi ˌseɪvɪŋ/','adj','tiết kiệm năng lượng','We use energy-saving appliances at home.','🔋'],
    ['power','/ˈpaʊə(r)/','n','năng lượng, điện năng','The storm cut power to the village.','⚡'],
    ['petrol','/ˈpetrəl/','n','xăng','Petrol is made from oil.','⛽']
  ]),

  11: rowsToWords4([
    ['future','/ˈfjuːtʃə(r)/','n/adj','tương lai','Transport may look very different in the future.','🔮'],
    ['travel','/ˈtrævl/','v/n','đi lại, du lịch','People may travel faster in the future.','🧳'],
    ['transportation','/ˌtrænspɔːˈteɪʃn/','n','sự vận chuyển, giao thông','New technology may change transportation.','🚌'],
    ['driverless car','/ˈdraɪvələs kɑː(r)/','n','ô tô không người lái','A driverless car can follow a programmed route.','🚘'],
    ['self-driving car','/ˌself ˈdraɪvɪŋ kɑː(r)/','n','xe tự lái','The self-driving car stops automatically.','🤖'],
    ['hover scooter','/ˈhɒvə ˌskuːtə(r)/','n','xe trượt lơ lửng','A hover scooter could move above the ground.','🛴'],
    ['bamboo-copter','/ˌbæmˈbuː ˌkɒptə(r)/','n','trực thăng tre tưởng tượng','The bamboo-copter is a creative future vehicle.','🚁'],
    ['skyTran','/ˈskaɪtræn/','n','hệ thống giao thông trên cao','SkyTran may carry passengers above busy streets.','🚝'],
    ['solar-powered ship','/ˌsəʊlə ˈpaʊəd ʃɪp/','n','tàu chạy bằng năng lượng mặt trời','The solar-powered ship uses sunlight for energy.','🚢'],
    ['electric bus','/ɪˌlektrɪk bʌs/','n','xe buýt điện','Electric buses can reduce city pollution.','🚌'],
    ['flying taxi','/ˈflaɪɪŋ ˌtæksi/','n','taxi bay','A flying taxi may carry people across the city.','🚕'],
    ['air taxi','/eə ˈtæksi/','n','taxi trên không','Air taxis could shorten travel time.','🚁'],
    ['high-speed train','/ˌhaɪ spiːd ˈtreɪn/','n','tàu cao tốc','The high-speed train connects two large cities.','🚄'],
    ['train','/treɪn/','n','tàu hỏa','Future trains may be faster and quieter.','🚆'],
    ['bus','/bʌs/','n','xe buýt','The bus may run on clean electricity.','🚌'],
    ['bicycle','/ˈbaɪsɪkl/','n','xe đạp','Bicycles will remain useful in green cities.','🚲'],
    ['motorbike','/ˈməʊtəbaɪk/','n','xe máy','Electric motorbikes are becoming more common.','🏍️'],
    ['ship','/ʃɪp/','n','tàu thủy','Future ships may use cleaner fuels.','🚢'],
    ['boat','/bəʊt/','n','thuyền','The small boat runs on solar power.','⛵'],
    ['plane','/pleɪn/','n','máy bay','Future planes may use greener technology.','✈️'],
    ['helicopter','/ˈhelɪkɒptə(r)/','n','trực thăng','The helicopter lands on a rooftop.','🚁'],
    ['comfortable seat','/ˈkʌmftəbl siːt/','n','ghế ngồi thoải mái','Passengers relax in comfortable seats.','💺'],
    ['convenient','/kənˈviːniənt/','adj','thuận tiện','Future transport should be fast and convenient.','👌'],
    ['fast','/fɑːst/','adj/adv','nhanh','This vehicle can travel very fast.','💨'],
    ['slow','/sləʊ/','adj/adv','chậm','Old transport can be slow in heavy traffic.','🐢'],
    ['safe','/seɪf/','adj','an toàn','Driverless systems should make travel safer.','🛡️'],
    ['unsafe','/ʌnˈseɪf/','adj','không an toàn','Travelling without a seat belt is unsafe.','⚠️'],
    ['environmentally friendly','/ɪnˌvaɪrənˈmentəli ˈfrendli/','adj','thân thiện với môi trường','Electric transport is more environmentally friendly.','🌿'],
    ['pollution-free','/pəˈluːʃn friː/','adj','không gây ô nhiễm','The city wants pollution-free public transport.','🍃'],
    ['automatic','/ˌɔːtəˈmætɪk/','adj','tự động','The doors open automatically at each station.','🤖'],
    ['modern','/ˈmɒdn/','adj','hiện đại','The city is building a modern transport system.','🏙️'],
    ['advanced','/ədˈvɑːnst/','adj','tiên tiến','The vehicle uses advanced technology.','🧠'],
    ['technology','/tekˈnɒlədʒi/','n','công nghệ','Technology is changing the way we travel.','💻'],
    ['invention','/ɪnˈvenʃn/','n','phát minh','The new vehicle is an exciting invention.','💡'],
    ['invent','/ɪnˈvent/','v','phát minh','Engineers hope to invent safer vehicles.','🛠️'],
    ['travel time','/ˈtrævl taɪm/','n','thời gian di chuyển','High-speed trains reduce travel time.','⏱️'],
    ['distance','/ˈdɪstəns/','n','khoảng cách','The vehicle can cover a long distance.','📏'],
    ['route','/ruːt/','n','tuyến đường','The computer chooses the best route.','🗺️'],
    ['station','/ˈsteɪʃn/','n','nhà ga, trạm','The train stops at every station.','🚉'],
    ['terminal','/ˈtɜːmɪnl/','n','nhà ga đầu cuối','Passengers wait at the transport terminal.','🏢'],
    ['passenger','/ˈpæsɪndʒə(r)/','n','hành khách','The vehicle can carry six passengers.','👥'],
    ['driver','/ˈdraɪvə(r)/','n','người lái xe','Future vehicles may not need a driver.','🧑‍✈️'],
    ['road','/rəʊd/','n','đường bộ','Smart roads may communicate with cars.','🛣️'],
    ['sky','/skaɪ/','n','bầu trời','Flying cars may travel through the sky.','☁️'],
    ['underground','/ˌʌndəˈɡraʊnd/','adj/adv','dưới lòng đất','Some future trains may travel underground.','🚇'],
    ['above ground','/əˌbʌv ˈɡraʊnd/','phrase','trên mặt đất','SkyTran runs above ground.','🚝'],
    ['carry','/ˈkæri/','v','chở, mang','The vehicle can carry four people.','🧳'],
    ['operate','/ˈɒpəreɪt/','v','vận hành','A computer can operate the vehicle.','🖥️'],
    ['move','/muːv/','v','di chuyển','The pod moves quietly along the track.','➡️']
  ]),

  12: rowsToWords4([
    ['Australia','/ɒˈstreɪliə/','n','Úc','Australia is famous for unique wildlife.','🇦🇺'],
    ['Canada','/ˈkænədə/','n','Canada','Canada has two official languages.','🇨🇦'],
    ['New Zealand','/ˌnjuː ˈziːlənd/','n','New Zealand','New Zealand is known for beautiful landscapes.','🇳🇿'],
    ['United Kingdom','/juˌnaɪtɪd ˈkɪŋdəm/','n','Vương quốc Anh','The United Kingdom includes four countries.','🇬🇧'],
    ['United States','/juˌnaɪtɪd ˈsteɪts/','n','Hoa Kỳ','The United States has fifty states.','🇺🇸'],
    ['Scotland','/ˈskɒtlənd/','n','Scotland','Scotland is famous for castles and lakes.','🏴'],
    ['England','/ˈɪŋɡlənd/','n','Anh','London is the capital of England and the UK.','🏴'],
    ['Wales','/weɪlz/','n','Xứ Wales','Wales has many mountains and castles.','🐉'],
    ['Northern Ireland','/ˌnɔːðən ˈaɪələnd/','n','Bắc Ireland','Northern Ireland is part of the United Kingdom.','🍀'],
    ['Ottawa','/ˈɒtəwə/','n','Ottawa','Ottawa is the capital of Canada.','🏛️'],
    ['Canberra','/ˈkænbərə/','n','Canberra','Canberra is the capital of Australia.','🏛️'],
    ['Wellington','/ˈwelɪŋtən/','n','Wellington','Wellington is the capital of New Zealand.','🏙️'],
    ['Washington DC','/ˌwɒʃɪŋtən ˌdiː ˈsiː/','n','Washington, D.C.','Washington DC is the capital of the United States.','🏛️'],
    ['London','/ˈlʌndən/','n','Luân Đôn','London has many famous tourist attractions.','🎡'],
    ['Edinburgh','/ˈedɪnbrə/','n','Edinburgh','Edinburgh is the capital of Scotland.','🏰'],
    ['Sydney','/ˈsɪdni/','n','Sydney','Sydney is famous for its harbour and opera house.','🌉'],
    ['Toronto','/təˈrɒntəʊ/','n','Toronto','Toronto is one of Canada’s largest cities.','🏙️'],
    ['Auckland','/ˈɔːklənd/','n','Auckland','Auckland is a major city in New Zealand.','🌆'],
    ['maple leaf','/ˈmeɪpl liːf/','n','lá phong','The maple leaf is a national symbol of Canada.','🍁'],
    ['kangaroo','/ˌkæŋɡəˈruː/','n','chuột túi','The kangaroo is an Australian animal.','🦘'],
    ['koala','/kəʊˈɑːlə/','n','gấu koala','Koalas live in Australia.','🐨'],
    ['kiwi','/ˈkiːwiː/','n','chim kiwi','The kiwi is a symbol of New Zealand.','🐦'],
    ['Maori','/ˈmaʊri/','n/adj','người Maori; thuộc Maori','Maori culture is important in New Zealand.','🌀'],
    ['Aboriginal','/ˌæbəˈrɪdʒənl/','adj/n','thuộc thổ dân Úc; thổ dân Úc','Aboriginal art has a long history.','🎨'],
    ['native people','/ˈneɪtɪv ˈpiːpl/','n','người bản địa','The museum teaches visitors about native people.','👥'],
    ['landmark','/ˈlændmɑːk/','n','địa danh nổi tiếng','The bridge is a famous city landmark.','📍'],
    ['tower','/ˈtaʊə(r)/','n','tòa tháp','The tower gives visitors a view of the city.','🗼'],
    ['museum','/mjuˈziːəm/','n','bảo tàng','The museum displays local history.','🏛️'],
    ['beach','/biːtʃ/','n','bãi biển','Australia has many beautiful beaches.','🏖️'],
    ['mountain','/ˈmaʊntən/','n','núi','New Zealand has spectacular mountains.','🏔️'],
    ['lake','/leɪk/','n','hồ','The lake is surrounded by green hills.','🏞️'],
    ['waterfall','/ˈwɔːtəfɔːl/','n','thác nước','Tourists hike to see the waterfall.','💦'],
    ['forest','/ˈfɒrɪst/','n','rừng','The national park protects a large forest.','🌲'],
    ['river','/ˈrɪvə(r)/','n','sông','The city lies beside a wide river.','🏞️'],
    ['national park','/ˌnæʃnəl ˈpɑːk/','n','vườn quốc gia','We saw wild animals in the national park.','🌳'],
    ['language','/ˈlæŋɡwɪdʒ/','n','ngôn ngữ','English is an international language.','🗣️'],
    ['official language','/əˌfɪʃl ˈlæŋɡwɪdʒ/','n','ngôn ngữ chính thức','English is an official language in many countries.','📜'],
    ['English','/ˈɪŋɡlɪʃ/','n/adj','tiếng Anh; thuộc Anh','English is widely spoken around the world.','🔤'],
    ['French','/frentʃ/','n/adj','tiếng Pháp; thuộc Pháp','French is also an official language in Canada.','🇫🇷'],
    ['climate','/ˈklaɪmət/','n','khí hậu','Australia has different climate zones.','🌦️'],
    ['culture','/ˈkʌltʃə(r)/','n','văn hóa','Food is an important part of local culture.','🎭'],
    ['cultural','/ˈkʌltʃərəl/','adj','thuộc văn hóa','The city holds many cultural events.','🎨'],
    ['traditional','/trəˈdɪʃənl/','adj','truyền thống','Visitors can enjoy traditional music.','🎶'],
    ['famous for','/ˈfeɪməs fɔː(r)/','phrase','nổi tiếng về','Canada is famous for its natural scenery.','⭐'],
    ['located','/ləʊˈkeɪtɪd/','adj','nằm ở, tọa lạc','The city is located on the coast.','📍'],
    ['north','/nɔːθ/','n/adj/adv','phía bắc','Canada lies to the north of the United States.','⬆️'],
    ['south','/saʊθ/','n/adj/adv','phía nam','Many beaches are in the south.','⬇️'],
    ['east','/iːst/','n/adj/adv','phía đông','The sun rises in the east.','➡️'],
    ['west','/west/','n/adj/adv','phía tây','They travelled west across the country.','⬅️'],
    ['visit','/ˈvɪzɪt/','v/n','thăm; chuyến thăm','I hope to visit New Zealand one day.','🧳'],
    ['tourist','/ˈtʊərɪst/','n','khách du lịch','Many tourists visit the castle every year.','📸']
  ])
};

Object.entries(VOCAB_EXTRA_4).forEach(([unitNo, extraWords]) => {
  const unit = VOCAB_DATA.find(item => item.unit === Number(unitNo));
  if (!unit) return;
  const seen = new Set(unit.words.map(item => item.word.trim().toLowerCase()));
  extraWords.forEach(item => {
    const key = item.word.trim().toLowerCase();
    if (!seen.has(key)) {
      unit.words.push(item);
      seen.add(key);
    }
  });
});