// Phase 4 vocabulary expansion: Units 7–9.
// Coverage targets follow the supplied Loigiaihay Global Success 7 unit pages.
// Practice examples are newly written; pronunciation continues to use browser TTS.

const rowsToWords3 = rows => rows.map(([word, ipa, type, vi, example, icon]) => ({word, ipa, type, vi, example, icon}));

const VOCAB_EXTRA_3 = {
  7: rowsToWords3([
    ['road','/rəʊd/','n','đường','This road is busy in the morning.','🛣️'],
    ['street','/striːt/','n','đường phố','Our school is on a quiet street.','🏙️'],
    ['lane','/leɪn/','n','làn đường','Stay in the correct lane.','↔️'],
    ['cycle lane','/ˈsaɪkl leɪn/','n','làn đường dành cho xe đạp','Cyclists should use the cycle lane.','🚲'],
    ['road user','/rəʊd ˈjuːzə(r)/','n','người tham gia giao thông','Every road user must follow the rules.','👥'],
    ['driver','/ˈdraɪvə(r)/','n','người lái xe','The driver stopped at the red light.','🚗'],
    ['passenger','/ˈpæsɪndʒə(r)/','n','hành khách','All passengers should wear seat belts.','💺'],
    ['motorist','/ˈməʊtərɪst/','n','người lái ô tô','Motorists must slow down near schools.','🚘'],
    ['bicycle','/ˈbaɪsɪkl/','n','xe đạp','I go to school by bicycle.','🚲'],
    ['bike','/baɪk/','n','xe đạp','Her bike has a small basket.','🚴'],
    ['motorbike','/ˈməʊtəbaɪk/','n','xe máy','My father rides a motorbike to work.','🏍️'],
    ['bus','/bʌs/','n','xe buýt','We take the bus to the city centre.','🚌'],
    ['car','/kɑː(r)/','n','ô tô','There are many cars on this road.','🚗'],
    ['train','/treɪn/','n','tàu hỏa','The train arrives at eight o’clock.','🚆'],
    ['plane','/pleɪn/','n','máy bay','The plane lands at the airport.','✈️'],
    ['boat','/bəʊt/','n','thuyền','They crossed the river by boat.','⛵'],
    ['ship','/ʃɪp/','n','tàu thủy','The ship carries many passengers.','🚢'],
    ['means of transport','/miːnz əv ˈtrænspɔːt/','n','phương tiện giao thông','The bicycle is a common means of transport.','🚦'],
    ['public transport','/ˌpʌblɪk ˈtrænspɔːt/','n','phương tiện giao thông công cộng','Public transport can reduce traffic jams.','🚌'],
    ['private vehicle','/ˈpraɪvət ˈviːəkl/','n','phương tiện cá nhân','Too many private vehicles cause congestion.','🚙'],
    ['cross','/krɒs/','v','băng qua','Look both ways before you cross.','🚸'],
    ['cross the road','/krɒs ðə rəʊd/','phrase','băng qua đường','Use the zebra crossing to cross the road.','🚶'],
    ['turn left','/tɜːn left/','phrase','rẽ trái','Turn left at the next traffic light.','⬅️'],
    ['turn right','/tɜːn raɪt/','phrase','rẽ phải','Turn right after the bridge.','➡️'],
    ['go straight','/ɡəʊ streɪt/','phrase','đi thẳng','Go straight for two hundred metres.','⬆️'],
    ['speed limit','/spiːd ˈlɪmɪt/','n','giới hạn tốc độ','The speed limit here is forty kilometres per hour.','4️⃣'],
    ['no parking','/nəʊ ˈpɑːkɪŋ/','phrase','cấm đỗ xe','This sign means no parking.','🅿️'],
    ['school ahead','/skuːl əˈhed/','phrase','phía trước có trường học','Drivers slow down when they see School Ahead.','🏫'],
    ['hospital ahead','/ˈhɒspɪtl əˈhed/','phrase','phía trước có bệnh viện','The Hospital Ahead sign is near the corner.','🏥'],
    ['traffic rule','/ˈtræfɪk ruːl/','n','quy tắc giao thông','This traffic rule keeps children safe.','📋'],
    ['follow traffic rules','/ˈfɒləʊ ˈtræfɪk ruːlz/','phrase','tuân thủ luật giao thông','We should follow traffic rules every day.','✅'],
    ['road safety','/rəʊd ˈseɪfti/','n','an toàn giao thông','Our class is learning about road safety.','🦺'],
    ['safe','/seɪf/','adj','an toàn','This crossing is safe for pedestrians.','✅'],
    ['dangerous','/ˈdeɪndʒərəs/','adj','nguy hiểm','Riding too fast is dangerous.','⚠️'],
    ['careful','/ˈkeəfl/','adj','cẩn thận','Be careful when you cross the street.','👀'],
    ['carefully','/ˈkeəfəli/','adv','một cách cẩn thận','She looked carefully before crossing.','🔎'],
    ['distance','/ˈdɪstəns/','n','khoảng cách','The distance from my home to school is three kilometres.','📏'],
    ['kilometre','/ˈkɪləmiːtə(r)/','n','ki-lô-mét','The station is one kilometre away.','📍'],
    ['far','/fɑː(r)/','adj/adv','xa','Is your school far from home?','🌐'],
    ['near','/nɪə(r)/','adj/adv','gần','There is a bus stop near my house.','📌'],
    ['allow','/əˈlaʊ/','v','cho phép','This road does not allow heavy trucks.','👍'],
    ['signal','/ˈsɪɡnəl/','n/v','tín hiệu; ra tín hiệu','Use a signal before you turn.','🚦'],
    ['traffic accident','/ˈtræfɪk ˌæksɪdənt/','n','tai nạn giao thông','Careless driving can cause a traffic accident.','🚑'],
    ['congestion','/kənˈdʒestʃən/','n','sự ùn tắc giao thông','The city has serious congestion at rush hour.','🚗'],
    ['reduce traffic','/rɪˈdjuːs ˈtræfɪk/','phrase','giảm giao thông, ùn tắc','More buses can help reduce traffic.','📉'],
    ['walking','/ˈwɔːkɪŋ/','n','việc đi bộ','Walking is healthy and eco-friendly.','🚶'],
    ['go on foot','/ɡəʊ ɒn fʊt/','phrase','đi bộ','I usually go on foot to the shop.','👟'],
    ['ride a bike','/raɪd ə baɪk/','phrase','đi xe đạp','She can ride a bike safely.','🚲'],
    ['drive a car','/draɪv ə kɑː(r)/','phrase','lái ô tô','My uncle drives a car to work.','🚗'],
    ['travel','/ˈtrævl/','v','đi lại, du lịch','We travel by train when possible.','🧳'],
    ['journey','/ˈdʒɜːni/','n','chuyến đi','The bus journey takes thirty minutes.','🚌']
  ]),

  8: rowsToWords3([
    ['film','/fɪlm/','n','phim','We watched a new film last night.','🎬'],
    ['movie','/ˈmuːvi/','n','phim','This movie is suitable for families.','🍿'],
    ['actor','/ˈæktə(r)/','n','nam diễn viên','The actor plays a brave police officer.','🎭'],
    ['actress','/ˈæktrəs/','n','nữ diễn viên','The actress won an award for the role.','🌟'],
    ['film star','/fɪlm stɑː(r)/','n','ngôi sao điện ảnh','The film star greeted fans after the premiere.','⭐'],
    ['scene','/siːn/','n','cảnh phim','My favourite scene happens near the end.','🎞️'],
    ['screen','/skriːn/','n','màn ảnh','The image looked huge on the cinema screen.','🖥️'],
    ['cinema','/ˈsɪnəmə/','n','rạp chiếu phim','We are going to the cinema on Saturday.','🎦'],
    ['audience','/ˈɔːdiəns/','n','khán giả','The audience laughed throughout the film.','👥'],
    ['ticket','/ˈtɪkɪt/','n','vé','I bought two cinema tickets online.','🎟️'],
    ['trailer','/ˈtreɪlə(r)/','n','đoạn giới thiệu phim','The trailer made the film look exciting.','📺'],
    ['soundtrack','/ˈsaʊndtræk/','n','nhạc phim','The soundtrack is beautiful and memorable.','🎵'],
    ['ending','/ˈendɪŋ/','n','phần kết','The ending surprised everyone.','🔚'],
    ['beginning','/bɪˈɡɪnɪŋ/','n','phần mở đầu','The beginning introduces the main characters.','▶️'],
    ['story','/ˈstɔːri/','n','câu chuyện','The film tells a touching story.','📖'],
    ['storyline','/ˈstɔːrilaɪn/','n','mạch truyện','The storyline is easy to follow.','🧵'],
    ['romantic comedy','/rəʊˌmæntɪk ˈkɒmədi/','n','phim hài lãng mạn','They watched a romantic comedy together.','💞'],
    ['thriller','/ˈθrɪlə(r)/','n','phim giật gân','The thriller kept us nervous until the end.','😰'],
    ['adventure film','/ədˈventʃə fɪlm/','n','phim phiêu lưu','The adventure film takes place in the jungle.','🗺️'],
    ['western','/ˈwestən/','n','phim miền Tây','The western has cowboys and horses.','🤠'],
    ['musical','/ˈmjuːzɪkl/','n','phim, vở nhạc kịch','The musical includes many songs and dances.','🎶'],
    ['cartoon','/kɑːˈtuːn/','n','phim hoạt hình','My little brother loves this cartoon.','🐭'],
    ['entertaining','/ˌentəˈteɪnɪŋ/','adj','mang tính giải trí','The film is light and entertaining.','😄'],
    ['boring','/ˈbɔːrɪŋ/','adj','nhàm chán','The middle of the film was boring.','🥱'],
    ['interesting','/ˈɪntrəstɪŋ/','adj','thú vị','The documentary is very interesting.','🧐'],
    ['predictable','/prɪˈdɪktəbl/','adj','dễ đoán','The ending was too predictable.','🔮'],
    ['surprising','/səˈpraɪzɪŋ/','adj','đáng ngạc nhiên','The final scene was surprising.','😮'],
    ['confusing','/kənˈfjuːzɪŋ/','adj','khó hiểu','The plot becomes confusing near the end.','🤔'],
    ['excellent','/ˈeksələnt/','adj','xuất sắc','The acting was excellent.','🏆'],
    ['fantastic','/fænˈtæstɪk/','adj','tuyệt vời','The special effects were fantastic.','✨'],
    ['disappointing','/ˌdɪsəˈpɔɪntɪŋ/','adj','đáng thất vọng','The sequel was disappointing.','😕'],
    ['violent','/ˈvaɪələnt/','adj','bạo lực','The film contains some violent scenes.','⚠️'],
    ['emotional','/ɪˈməʊʃənl/','adj','giàu cảm xúc','The final speech is very emotional.','🥹'],
    ['enjoyable','/ɪnˈdʒɔɪəbl/','adj','thú vị, dễ thưởng thức','It is an enjoyable family film.','😊'],
    ['funny','/ˈfʌni/','adj','buồn cười','The supporting character is very funny.','😂'],
    ['sad','/sæd/','adj','buồn','The story has a sad ending.','😢'],
    ['exciting','/ɪkˈsaɪtɪŋ/','adj','hấp dẫn, thú vị','The chase scene is exciting.','🤩'],
    ['dull','/dʌl/','adj','tẻ nhạt','The first twenty minutes felt dull.','😐'],
    ['recommend','/ˌrekəˈmend/','v','giới thiệu, khuyên xem','I recommend this film to science-fiction fans.','👍'],
    ['release','/rɪˈliːs/','v/n','phát hành; sự phát hành','The studio will release the film in June.','📅'],
    ['direct','/dəˈrekt/','v','đạo diễn','She wants to direct her own short film.','🎥'],
    ['act','/ækt/','v','diễn xuất','He can act and sing well.','🎭'],
    ['star','/stɑː(r)/','v/n','đóng vai chính; ngôi sao','A young actor stars in the new film.','⭐'],
    ['rating','/ˈreɪtɪŋ/','n','điểm đánh giá, xếp hạng','The film has a high audience rating.','📊'],
    ['special effects','/ˌspeʃl ɪˈfekts/','n','hiệu ứng đặc biệt','The special effects make the monsters look real.','💥'],
    ['visual effects','/ˌvɪʒuəl ɪˈfekts/','n','hiệu ứng hình ảnh','The visual effects are impressive.','🌌'],
    ['award','/əˈwɔːd/','n','giải thưởng','The film received an international award.','🏆'],
    ['film festival','/fɪlm ˈfestɪvl/','n','liên hoan phim','The director presented the movie at a film festival.','🎪'],
    ['main character','/meɪn ˈkærəktə(r)/','n','nhân vật chính','The main character learns an important lesson.','🦸'],
    ['supporting character','/səˈpɔːtɪŋ ˈkærəktə(r)/','n','nhân vật phụ','The supporting character is very memorable.','👤'],
    ['villain','/ˈvɪlən/','n','nhân vật phản diện','The villain wants to control the city.','😈'],
    ['hero','/ˈhɪərəʊ/','n','người hùng, nhân vật chính diện','The hero saves the village.','🦸‍♂️'],
    ['subtitle','/ˈsʌbtaɪtl/','n','phụ đề','I watch English films with Vietnamese subtitles.','💬']
  ]),

  9: rowsToWords3([
    ['celebrate','/ˈselɪbreɪt/','v','kỷ niệm, tổ chức lễ','People celebrate the festival with music and food.','🎉'],
    ['celebration','/ˌselɪˈbreɪʃn/','n','lễ kỷ niệm, sự ăn mừng','The celebration lasts for three days.','🥳'],
    ['traditional','/trəˈdɪʃənl/','adj','truyền thống','People wear traditional clothes at the festival.','👘'],
    ['cultural','/ˈkʌltʃərəl/','adj','thuộc văn hóa','The event includes many cultural activities.','🎭'],
    ['annual','/ˈænjuəl/','adj','hằng năm','This annual festival happens every spring.','📅'],
    ['harvest','/ˈhɑːvɪst/','n/v','vụ thu hoạch; thu hoạch','The festival celebrates the rice harvest.','🌾'],
    ['turkey','/ˈtɜːki/','n','gà tây','Roast turkey is common at Thanksgiving.','🦃'],
    ['cranberry sauce','/ˈkrænbəri sɔːs/','n','sốt nam việt quất','They serve cranberry sauce with turkey.','🍒'],
    ['family gathering','/ˈfæməli ˈɡæðərɪŋ/','n','buổi họp mặt gia đình','Thanksgiving is a time for family gatherings.','👨‍👩‍👧‍👦'],
    ['special food','/ˈspeʃl fuːd/','n','món ăn đặc biệt','Every festival has its own special food.','🍽️'],
    ['procession','/prəˈseʃn/','n','đoàn rước','A colourful procession moves through the town.','🥁'],
    ['ceremony','/ˈserəməni/','n','nghi lễ','The opening ceremony begins at nine.','🎖️'],
    ['attend','/əˈtend/','v','tham dự','Thousands of visitors attend the festival.','🙋'],
    ['take place','/teɪk pleɪs/','phrase','diễn ra','The festival takes place in February.','📆'],
    ['festival-goer','/ˈfestɪvl ˌɡəʊə(r)/','n','người tham dự lễ hội','Festival-goers filled the main square.','👥'],
    ['joyful','/ˈdʒɔɪfl/','adj','vui vẻ, hân hoan','The parade creates a joyful atmosphere.','😄'],
    ['crowded','/ˈkraʊdɪd/','adj','đông đúc','The streets become crowded during the festival.','🚶‍♀️'],
    ['colourful','/ˈkʌləfl/','adj','đầy màu sắc','The dancers wear colourful costumes.','🌈'],
    ['traditional costume','/trəˈdɪʃənl ˈkɒstjuːm/','n','trang phục truyền thống','She wore a traditional costume in the parade.','🥻'],
    ['traditional dish','/trəˈdɪʃənl dɪʃ/','n','món ăn truyền thống','Visitors can try a traditional dish at the market.','🍲'],
    ['folk dance','/fəʊk dɑːns/','n','điệu múa dân gian','Students performed a folk dance.','💃'],
    ['dance performance','/dɑːns pəˈfɔːməns/','n','màn biểu diễn múa','The dance performance opened the festival.','🕺'],
    ['competition','/ˌkɒmpəˈtɪʃn/','n','cuộc thi','There is a cooking competition this afternoon.','🏆'],
    ['symbol','/ˈsɪmbl/','n','biểu tượng','The lantern is a symbol of the festival.','🏮'],
    ['candle','/ˈkændl/','n','nến','They put a candle inside the lantern.','🕯️'],
    ['light candles','/laɪt ˈkændlz/','phrase','thắp nến','Families light candles in the evening.','🕯️'],
    ['paint eggs','/peɪnt eɡz/','phrase','tô màu trứng','Children paint eggs before Easter.','🎨'],
    ['Easter egg','/ˈiːstə eɡ/','n','trứng Phục sinh','She found an Easter egg in the garden.','🥚'],
    ['egg hunt','/eɡ hʌnt/','n','trò săn trứng','The children joined an egg hunt.','🔍'],
    ['pumpkin','/ˈpʌmpkɪn/','n','bí ngô','They bought a large pumpkin for Halloween.','🎃'],
    ['mask','/mɑːsk/','n','mặt nạ','He wore a scary mask.','🎭'],
    ['costume party','/ˈkɒstjuːm ˌpɑːti/','n','tiệc hóa trang','We had a costume party at school.','🥳'],
    ['trick or treat','/ˌtrɪk ɔː ˈtriːt/','phrase','trò xin kẹo Halloween','Children say trick or treat at neighbours’ doors.','🍬'],
    ['flower','/ˈflaʊə(r)/','n','hoa','The street is decorated with flowers.','🌸'],
    ['temple','/ˈtempl/','n','đền, chùa','People visit the temple during the festival.','⛩️'],
    ['worship','/ˈwɜːʃɪp/','v','thờ cúng','Some families worship their ancestors.','🙏'],
    ['local festival','/ˈləʊkl ˈfestɪvl/','n','lễ hội địa phương','The village holds a local festival every year.','🎪'],
    ['national festival','/ˈnæʃnəl ˈfestɪvl/','n','lễ hội quốc gia','The national festival attracts visitors from abroad.','🏳️'],
    ['Mid-Autumn Festival','/ˌmɪd ˈɔːtəm ˈfestɪvl/','n','Tết Trung thu','Children carry lanterns at the Mid-Autumn Festival.','🏮'],
    ['Christmas','/ˈkrɪsməs/','n','Lễ Giáng sinh','Families decorate trees at Christmas.','🎄'],
    ['New Year','/ˌnjuː ˈjɪə(r)/','n','Năm mới','We wish everyone happiness at New Year.','🎊'],
    ["New Year's Eve",'/ˌnjuː jɪəz ˈiːv/','n','đêm Giao thừa','People watch fireworks on New Year’s Eve.','🎆'],
    ['music performance','/ˈmjuːzɪk pəˈfɔːməns/','n','màn biểu diễn âm nhạc','A music performance starts after the parade.','🎤'],
    ['special occasion','/ˈspeʃl əˈkeɪʒn/','n','dịp đặc biệt','We wear our best clothes on special occasions.','🎁'],
    ['gather','/ˈɡæðə(r)/','v','tụ họp','Families gather for a big meal.','👨‍👩‍👧‍👦'],
    ['exchange gifts','/ɪksˈtʃeɪndʒ ɡɪfts/','phrase','trao đổi quà','Friends exchange gifts during the celebration.','🎁'],
    ['give thanks','/ɡɪv θæŋks/','phrase','bày tỏ lòng biết ơn','People give thanks for the good things in life.','🙏']
  ])
};

Object.entries(VOCAB_EXTRA_3).forEach(([unitNo, extraWords]) => {
  const unit = VOCAB_DATA.find(item => item.unit === Number(unitNo));
  if (!unit) return;
  const seen = new Set(unit.words.map(item => item.word.trim().toLowerCase()));
  extraWords.forEach(item => {
    const key = item.word.trim().toLowerCase();
    if (!seen.has(key)) {
      unit.words.push(item);
      seen.add(key);
    }
  });
});